/* Auto-generated by oz_transpile -- do not edit */
#include "oz_dispatch.h"
#include "OZObject_ozh.h"
#include "Controller_ozh.h"
#include "Sensor_ozh.h"

const char *const oz_class_names[OZ_CLASS_COUNT] = {
	[OZ_CLASS_OZObject] = "OZObject",
	[OZ_CLASS_Controller] = "Controller",
	[OZ_CLASS_Sensor] = "Sensor",
};

const uint8_t oz_superclass_id[OZ_CLASS_COUNT] = {
	[OZ_CLASS_OZObject] = OZ_CLASS_COUNT,
	[OZ_CLASS_Controller] = OZ_CLASS_OZObject,
	[OZ_CLASS_Sensor] = OZ_CLASS_OZObject,
};

OZ_fn_dealloc OZ_vtable_dealloc[OZ_CLASS_COUNT];
OZ_fn_init OZ_vtable_init[OZ_CLASS_COUNT];

__attribute__((constructor))
static void oz_register_vtables(void)
{
	OZ_vtable_dealloc[OZ_CLASS_OZObject] = (OZ_fn_dealloc)OZObject_dealloc;
	OZ_vtable_dealloc[OZ_CLASS_Controller] = (OZ_fn_dealloc)Controller_dealloc;
	OZ_vtable_dealloc[OZ_CLASS_Sensor] = (OZ_fn_dealloc)Sensor_dealloc;
	OZ_vtable_init[OZ_CLASS_OZObject] = (OZ_fn_init)OZObject_init;
	OZ_vtable_init[OZ_CLASS_Controller] = (OZ_fn_init)OZObject_init;
	OZ_vtable_init[OZ_CLASS_Sensor] = (OZ_fn_init)OZObject_init;
}

void OZObject_dispatch_free(struct OZObject *obj)
{
	switch (obj->oz_class_id) {
	case OZ_CLASS_OZObject: OZObject_free((struct OZObject *)obj); break;
	case OZ_CLASS_Controller: Controller_free((struct Controller *)obj); break;
	case OZ_CLASS_Sensor: Sensor_free((struct Sensor *)obj); break;
	default: break;
	}
}
