/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include <stdint.h>
#include <stdbool.h>

#ifndef BOOL
#define BOOL _Bool
#endif

struct OZObject;
struct Controller;
struct Sensor;

typedef struct OZObject *id;

enum oz_class_id_enum {
	OZ_CLASS_OZObject = 0,
	OZ_CLASS_Controller = 1,
	OZ_CLASS_Sensor = 2,
	OZ_CLASS_COUNT = 3
};

/* Class introspection tables */
extern const char *const oz_class_names[OZ_CLASS_COUNT];
extern const uint8_t oz_superclass_id[OZ_CLASS_COUNT];

static inline const char *oz_name(uint8_t class_id)
{
	return oz_class_names[class_id];
}

static inline uint8_t oz_superclass(uint8_t class_id)
{
	return oz_superclass_id[class_id];
}

static inline bool oz_isKindOfClass(uint8_t class_id, uint8_t target_class_id)
{
	uint8_t cur = class_id;
	while (cur != OZ_CLASS_COUNT) {
		if (cur == target_class_id) {
			return true;
		}
		cur = oz_superclass_id[cur];
	}
	return false;
}


void OZObject_dispatch_free(struct OZObject *obj);

/* OZLog — formatted logging with %@ object support */
void OZLog(const char *fmt, ...);
int _oz_get_log_precision(void);
