/* Auto-generated by oz_transpile -- do not edit */
#include "oz_mem_slabs.h"

OZ_SLAB_DEFINE(oz_slab_OZObject, sizeof(struct OZObject), 1, 4);
OZ_SLAB_DEFINE(oz_slab_Controller, sizeof(struct Controller), 1, 4);
OZ_SLAB_DEFINE(oz_slab_Sensor, sizeof(struct Sensor), 1, 4);
