/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "platform/oz_platform.h"
#include "oz_dispatch.h"
#include "OZObject_ozh.h"

struct OZLed {
	struct OZObject base;
	int _pin;
	BOOL _state;
};

struct OZLed * OZLed_initWithPin_(struct OZLed *self, int pin);
struct OZLed * OZLed_init(struct OZLed *self);
void OZLed_toggle(struct OZLed *self);
void OZLed_turnOn(struct OZLed *self);
int OZLed_pin(struct OZLed *self);
void OZLed_dealloc(struct OZLed *self);

