/* Auto-generated by oz_transpile -- do not edit */
#include "OZLed_ozh.h"
#include "OZObject_ozh.h"

OZ_SLAB_DEFINE(oz_slab_OZLed, sizeof(struct OZLed), 1, 4);

struct OZLed * OZLed_initWithPin_(struct OZLed *self, int pin)
{
	OZObject_init((struct OZObject *)self);
	self->_pin = pin;
	return self;
}
struct OZLed * OZLed_init(struct OZLed *self)
{
	return self;
}
void OZLed_toggle(struct OZLed *self)
{
	self->_state = !self->_state;
}
void OZLed_turnOn(struct OZLed *self)
{
	self->_state = 1;
}
int OZLed_pin(struct OZLed *self)
{
	return self->_pin;
}
void OZLed_dealloc(struct OZLed *self)
{
	OZObject_dealloc((struct OZObject *)self);
}
