/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "oz/platform/oz_platform.h"
#include <string.h>

#include "OZObject.h"
#include "OZLed.h"

extern oz_slab_t oz_slab_OZObject;
extern oz_slab_t oz_slab_OZLed;

static inline struct OZObject *OZObject_alloc(void)
{
	struct OZObject *obj;
	if (oz_slab_alloc(&oz_slab_OZObject, (void **)&obj) != 0) {
		return (struct OZObject *)0;
	}
	memset(obj, 0, sizeof(struct OZObject));
	obj->oz_class_id = OZ_CLASS_OZObject;
	oz_atomic_init(&obj->_refcount, 1);
	return obj;
}

static inline void OZObject_free(struct OZObject *obj)
{
	oz_slab_free(&oz_slab_OZObject, (void *)obj);
}

static inline struct OZLed *OZLed_alloc(void)
{
	struct OZLed *obj;
	if (oz_slab_alloc(&oz_slab_OZLed, (void **)&obj) != 0) {
		return (struct OZLed *)0;
	}
	memset(obj, 0, sizeof(struct OZLed));
	obj->base.oz_class_id = OZ_CLASS_OZLed;
	oz_atomic_init(&obj->base._refcount, 1);
	return obj;
}

static inline void OZLed_free(struct OZLed *obj)
{
	oz_slab_free(&oz_slab_OZLed, (void *)obj);
}

static inline void OZObject_dispatch_free(struct OZObject *obj)
{
	switch (obj->oz_class_id) {
	case OZ_CLASS_OZObject: OZObject_free((struct OZObject *)obj); break;
	case OZ_CLASS_OZLed: OZLed_free((struct OZLed *)obj); break;
	default: break;
	}
}

