/* Auto-generated by oz_transpile -- do not edit */
#include "oz_dispatch.h"
#include "OZObject_ozh.h"
#include "Logger_ozh.h"
#include "Timer_ozh.h"

const char *const oz_class_names[OZ_CLASS_COUNT] = {
	[OZ_CLASS_OZObject] = "OZObject",
	[OZ_CLASS_Logger] = "Logger",
	[OZ_CLASS_Timer] = "Timer",
};

const uint8_t oz_superclass_id[OZ_CLASS_COUNT] = {
	[OZ_CLASS_OZObject] = OZ_CLASS_COUNT,
	[OZ_CLASS_Logger] = OZ_CLASS_OZObject,
	[OZ_CLASS_Timer] = OZ_CLASS_OZObject,
};

/* Weak default: returns -1 (no precision override).
 * OZLog.c provides the strong definition on Zephyr. */
__attribute__((weak)) int _oz_get_log_precision(void) { return -1; }

void OZObject_dispatch_free(struct OZObject *obj)
{
	switch (obj->_meta.class_id) {
	case OZ_CLASS_OZObject: OZObject_free((struct OZObject *)obj); break;
	case OZ_CLASS_Logger: Logger_free((struct Logger *)obj); break;
	case OZ_CLASS_Timer: Timer_free((struct Timer *)obj); break;
	default: break;
	}
}
