/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include <stdint.h>
#include <stdbool.h>

#ifndef BOOL
#define BOOL _Bool
#endif

struct OZObject;
struct Circle;
struct Square;

typedef struct OZObject *id;

enum oz_class_id {
	OZ_CLASS_OZObject = 0,
	OZ_CLASS_Circle = 1,
	OZ_CLASS_Square = 2,
	OZ_CLASS_COUNT = 3
};

/* Class introspection tables */
extern const char *const oz_class_names[OZ_CLASS_COUNT];
extern const uint8_t oz_superclass_id[OZ_CLASS_COUNT];

static inline const char *oz_name(uint8_t class_id)
{
	return oz_class_names[class_id];
}

static inline uint8_t oz_superclass(uint8_t class_id)
{
	return oz_superclass_id[class_id];
}

static inline bool oz_isKindOfClass(uint8_t class_id, uint8_t target_class_id)
{
	uint8_t cur = class_id;
	while (cur != OZ_CLASS_COUNT) {
		if (cur == target_class_id) {
			return true;
		}
		cur = oz_superclass_id[cur];
	}
	return false;
}

/* Protocol dispatch function pointer types */
typedef int (*OZ_fn_color)(struct OZObject *);
typedef void (*OZ_fn_draw)(struct OZObject *);

/* Compile-time dispatch: OZ_IMPL macros map class x selector -> direct function */
#define OZ_IMPL_Circle_color(self, ...)	Circle_color((struct Circle *)(self), ##__VA_ARGS__)
#define OZ_IMPL_Square_color(self, ...)	Square_color((struct Square *)(self), ##__VA_ARGS__)
#define OZ_IMPL_Circle_draw(self, ...)	Circle_draw((struct Circle *)(self), ##__VA_ARGS__)
#define OZ_IMPL_Square_draw(self, ...)	Square_draw((struct Square *)(self), ##__VA_ARGS__)

/* Static dispatch: token concatenation resolves at compile time */
#define OZ_SEND(cls, sel, self, ...) OZ_IMPL_##cls##_##sel((self), ##__VA_ARGS__)

/* Const protocol dispatch tables (indexed by oz_class_id) */
extern const OZ_fn_color OZ_PROTOCOL_RESOLVE_color[OZ_CLASS_COUNT];
extern const OZ_fn_draw OZ_PROTOCOL_RESOLVE_draw[OZ_CLASS_COUNT];

/* OZ_PROTOCOL_SEND macros — polymorphic fallback, caller must ensure obj has no side effects */
#define OZ_PROTOCOL_SEND_color(obj) OZ_PROTOCOL_RESOLVE_color[((struct OZObject *)(obj))->oz_class_id]((struct OZObject *)(obj))
#define OZ_PROTOCOL_SEND_draw(obj) OZ_PROTOCOL_RESOLVE_draw[((struct OZObject *)(obj))->oz_class_id]((struct OZObject *)(obj))


void OZObject_dispatch_free(struct OZObject *obj);

/* OZLog — formatted logging with %@ object support */
void OZLog(const char *fmt, ...);
