/* Auto-generated by oz_transpile -- do not edit */
#include "oz_dispatch.h"
#include "OZObject_ozh.h"
#include "Circle_ozh.h"
#include "Square_ozh.h"

const char *const oz_class_names[OZ_CLASS_COUNT] = {
	[OZ_CLASS_OZObject] = "OZObject",
	[OZ_CLASS_Circle] = "Circle",
	[OZ_CLASS_Square] = "Square",
};

const uint8_t oz_superclass_id[OZ_CLASS_COUNT] = {
	[OZ_CLASS_OZObject] = OZ_CLASS_COUNT,
	[OZ_CLASS_Circle] = OZ_CLASS_OZObject,
	[OZ_CLASS_Square] = OZ_CLASS_OZObject,
};

const OZ_fn_color OZ_PROTOCOL_RESOLVE_color[OZ_CLASS_COUNT] = {
	[OZ_CLASS_Circle] = (OZ_fn_color)Circle_color,
	[OZ_CLASS_Square] = (OZ_fn_color)Square_color,
};

const OZ_fn_draw OZ_PROTOCOL_RESOLVE_draw[OZ_CLASS_COUNT] = {
	[OZ_CLASS_Circle] = (OZ_fn_draw)Circle_draw,
	[OZ_CLASS_Square] = (OZ_fn_draw)Square_draw,
};

void OZObject_dispatch_free(struct OZObject *obj)
{
	switch (obj->_meta.class_id) {
	case OZ_CLASS_OZObject: OZObject_free((struct OZObject *)obj); break;
	case OZ_CLASS_Circle: Circle_free((struct Circle *)obj); break;
	case OZ_CLASS_Square: Square_free((struct Square *)obj); break;
	default: break;
	}
}
