/* Auto-generated by oz_transpile -- do not edit */
#include "OZObject_ozh.h"
#include "Circle_ozh.h"
#include "Square_ozh.h"

OZ_SLAB_DEFINE(oz_slab_OZObject, sizeof(struct OZObject), 1, 4);

struct OZObject *OZObject_retain(struct OZObject *self)
{
	if (self) {
		oz_atomic_inc(&self->_refcount);
	}
	return self;
}

void OZObject_release(struct OZObject *self)
{
	if (!self) {
		return;
	}
	if (oz_atomic_dec_and_test(&self->_refcount)) {
		OZ_PROTOCOL_SEND_dealloc((struct OZObject *)self);
	}
}

uint32_t OZObject_retainCount(struct OZObject *self)
{
	if (!self) {
		return 0;
	}
	return (uint32_t)oz_atomic_get(&self->_refcount);
}
BOOL OZObject_isEqual_(struct OZObject *self, struct OZObject *anObject)
{
	return self == anObject;
}

int OZObject_cDescription_maxLength_(struct OZObject *self, char *buf, int maxLen)
{
	return oz_platform_snprint(buf, (size_t)maxLen, "<%s: %p>",
		oz_class_names[self->oz_class_id], (void *)self);
}
struct OZObject * OZObject_init(struct OZObject *self)
{
	return self;
}
void OZObject_dealloc(struct OZObject *self)
{
	OZObject_dispatch_free((struct OZObject *)self);
}
