#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate a Unity test_main.c from test_* function signatures."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

TEST_FUNC_RE = re.compile(r"^\s*void\s+(test_\w+)\s*\(\s*void\s*\)", re.MULTILINE)
SETUP_RE = re.compile(r"^\s*void\s+setUp\s*\(\s*void\s*\)", re.MULTILINE)
TEARDOWN_RE = re.compile(r"^\s*void\s+tearDown\s*\(\s*void\s*\)", re.MULTILINE)


def discover_tests(paths: list[Path]) -> tuple[list[str], bool, bool]:
    """Scan files for void test_*(void) signatures and setUp/tearDown."""
    names: list[str] = []
    has_setup = False
    has_teardown = False
    for p in paths:
        text = p.read_text()
        names.extend(TEST_FUNC_RE.findall(text))
        if SETUP_RE.search(text):
            has_setup = True
        if TEARDOWN_RE.search(text):
            has_teardown = True
    return names, has_setup, has_teardown


def generate_main(test_names: list[str],
                  has_setup: bool = False,
                  has_teardown: bool = False) -> str:
    """Generate Unity test_main.c content."""
    externs = "\n".join(f"extern void {n}(void);" for n in test_names)
    runs = "\n\t".join(f"RUN_TEST({n});" for n in test_names)
    setup_str = "extern void setUp(void);" if has_setup else "void setUp(void) {}"
    teardown_str = "extern void tearDown(void);" if has_teardown else "void tearDown(void) {}"
    return f"""\
/* Auto-generated by gen_test_main.py -- do not edit */
#include "unity.h"

{externs}

{setup_str}
{teardown_str}

int main(void)
{{
\tUNITY_BEGIN();
\t{runs}
\treturn UNITY_END();
}}
"""


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Generate Unity main() from test signatures")
    p.add_argument("--scan", required=True, nargs="+", help="Files to scan for test_* functions")
    p.add_argument("--output", required=True, help="Output path for test_main.c")
    args = p.parse_args(argv)

    paths = [Path(f) for f in args.scan]
    names, has_setup, has_teardown = discover_tests(paths)
    if not names:
        print("gen_test_main: error: no test_* functions found", file=sys.stderr)
        return 1

    Path(args.output).write_text(generate_main(names, has_setup, has_teardown))
    return 0


if __name__ == "__main__":
    sys.exit(main())
