#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate a Unity test_main.c from test_* function signatures."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

TEST_FUNC_RE = re.compile(r"^\s*void\s+(test_\w+)\s*\(\s*void\s*\)", re.MULTILINE)
SETUP_RE = re.compile(r"^\s*void\s+setUp\s*\(\s*void\s*\)", re.MULTILINE)
TEARDOWN_RE = re.compile(r"^\s*void\s+tearDown\s*\(\s*void\s*\)", re.MULTILINE)


def discover_tests(paths: list[Path]) -> tuple[list[str], bool, bool]:
    """Scan files for void test_*(void) signatures and setUp/tearDown."""
    names: list[str] = []
    has_setup = False
    has_teardown = False
    for p in paths:
        text = p.read_text()
        names.extend(TEST_FUNC_RE.findall(text))
        if SETUP_RE.search(text):
            has_setup = True
        if TEARDOWN_RE.search(text):
            has_teardown = True
    return names, has_setup, has_teardown


#: The census epilogue, appended after `UNITY_END()` when `--census` names
#: the header that declares `oz_check_all_slabs` (#451).
#:
#: After UNITY_END, not before: a case's own `tearDown` has run by then, so
#: anything it releases is already back in its slab and does not report as
#: a leak.
#:
#: The Unity result is still returned when the census is clean, so a real
#: assertion failure keeps its own exit code. The `1` is only reached when
#: Unity itself passed and the census did not -- which is exactly the
#: signal this exists for, and is how a leak is told apart from a failed
#: assertion by reading the output rather than the status alone.
CENSUS_EPILOGUE = """\

\t/* Exit-time live-object census (#451): every slab block this run handed
\t * out must have been handed back. A non-zero answer names each class on
\t * stderr. This catches what the LSan job cannot -- an unreleased object
\t * still reachable from a file-scope static or a static-storage ivar
\t * chain -- and it runs at every compiler and -O cell, with no sanitizer.
\t */
\tif (oz_check_all_slabs() > 0) {
\t\treturn 1;
\t}
\treturn failures;
"""


def generate_main(test_names: list[str],
                  has_setup: bool = False,
                  has_teardown: bool = False,
                  census_header: str | None = None) -> str:
    """Generate Unity test_main.c content.

    `census_header` is the generated companion header that declares
    `oz_check_all_slabs` -- `oz2c_dispatch.h` for a transpiled case. It is
    included rather than the prototype being written out here, so a change
    to the census's signature is a compile error instead of a silent
    mismatch across translation units. Passing None (the PAL's own C
    tests, which have no generated companion) emits the plain main().
    """
    externs = "\n".join(f"extern void {n}(void);" for n in test_names)
    runs = "\n\t".join(f"RUN_TEST({n});" for n in test_names)
    setup_str = "extern void setUp(void);" if has_setup else "void setUp(void) {}"
    teardown_str = "extern void tearDown(void);" if has_teardown else "void tearDown(void) {}"
    census_include = f'\n#include "{census_header}"' if census_header else ""
    body = CENSUS_EPILOGUE if census_header else "\treturn failures;\n"
    return f"""\
/* Auto-generated by gen_test_main.py -- do not edit */
#include "unity.h"{census_include}

{externs}

{setup_str}
{teardown_str}

int main(void)
{{
\tint failures;

\tUNITY_BEGIN();
\t{runs}
\tfailures = UNITY_END();
{body}}}
"""


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Generate Unity main() from test signatures")
    p.add_argument("--scan", required=True, nargs="+", help="Files to scan for test_* functions")
    p.add_argument("--output", required=True, help="Output path for test_main.c")
    p.add_argument("--census", metavar="HEADER", default=None,
                   help="Header declaring oz_check_all_slabs (e.g. oz2c_dispatch.h); "
                        "call the exit-time live-object census after UNITY_END() and "
                        "fail the run when it reports an outstanding allocation")
    args = p.parse_args(argv)

    paths = [Path(f) for f in args.scan]
    names, has_setup, has_teardown = discover_tests(paths)
    if not names:
        print("gen_test_main: error: no test_* functions found", file=sys.stderr)
        return 1

    Path(args.output).write_text(
        generate_main(names, has_setup, has_teardown, census_header=args.census))
    return 0


if __name__ == "__main__":
    sys.exit(main())
