CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_CPP_RTTI=n
CONFIG_CPP_EXCEPTIONS=n
CONFIG_SYS_HEAP_RUNTIME_STATS=y
CONFIG_PRINTK=y
CONFIG_TIMESLICING=n
CONFIG_PM=n
CONFIG_MAIN_STACK_SIZE=4096
