CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_CPP_RTTI=y
CONFIG_CPP_EXCEPTIONS=n
CONFIG_TIMING_FUNCTIONS=y
CONFIG_TIMESLICING=n
CONFIG_PM=n
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=8192
CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=8192
