/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include <stdint.h>
#include <stdbool.h>

#ifndef BOOL
#define BOOL _Bool
#endif

struct OZObject;
struct EmptyClass;

typedef struct OZObject *id;

enum oz_class_id {
	OZ_CLASS_OZObject = 0,
	OZ_CLASS_EmptyClass = 1,
	OZ_CLASS_COUNT = 2
};

/* Class introspection tables */
extern const char *const oz_class_names[OZ_CLASS_COUNT];
extern const uint8_t oz_superclass_id[OZ_CLASS_COUNT];

static inline const char *oz_name(uint8_t class_id)
{
	return oz_class_names[class_id];
}

static inline uint8_t oz_superclass(uint8_t class_id)
{
	return oz_superclass_id[class_id];
}

static inline bool oz_isKindOfClass(uint8_t class_id, uint8_t target_class_id)
{
	uint8_t cur = class_id;
	while (cur != OZ_CLASS_COUNT) {
		if (cur == target_class_id) {
			return true;
		}
		cur = oz_superclass_id[cur];
	}
	return false;
}

/* Protocol dispatch function pointer types */
typedef void (*OZ_fn_dealloc)(struct OZObject *);
typedef struct OZObject * (*OZ_fn_init)(struct OZObject *);

/* Protocol dispatch tables (indexed by oz_class_id) */
extern OZ_fn_dealloc OZ_vtable_dealloc[OZ_CLASS_COUNT];
extern OZ_fn_init OZ_vtable_init[OZ_CLASS_COUNT];

/* OZ_SEND macros — caller must ensure obj has no side effects */
#define OZ_SEND_dealloc(obj) OZ_vtable_dealloc[((struct OZObject *)(obj))->oz_class_id]((struct OZObject *)(obj))
#define OZ_SEND_init(obj) OZ_vtable_init[((struct OZObject *)(obj))->oz_class_id]((struct OZObject *)(obj))


void OZObject_dispatch_free(struct OZObject *obj);

/* OZLog — formatted logging with %@ object support */
void OZLog(const char *fmt, ...);
