/* Auto-generated by oz_transpile -- do not edit */
#include "oz_dispatch.h"
#include "OZObject_ozh.h"
#include "OZLed_ozh.h"

const char *const oz_class_names[OZ_CLASS_COUNT] = {
	[OZ_CLASS_OZObject] = "OZObject",
	[OZ_CLASS_OZLed] = "OZLed",
};

const uint8_t oz_superclass_id[OZ_CLASS_COUNT] = {
	[OZ_CLASS_OZObject] = OZ_CLASS_COUNT,
	[OZ_CLASS_OZLed] = OZ_CLASS_OZObject,
};

OZ_fn_dealloc OZ_vtable_dealloc[OZ_CLASS_COUNT];
OZ_fn_init OZ_vtable_init[OZ_CLASS_COUNT];
OZ_fn_toggle OZ_vtable_toggle[OZ_CLASS_COUNT];

__attribute__((constructor))
static void oz_register_vtables(void)
{
	OZ_vtable_dealloc[OZ_CLASS_OZObject] = (OZ_fn_dealloc)OZObject_dealloc;
	OZ_vtable_dealloc[OZ_CLASS_OZLed] = (OZ_fn_dealloc)OZLed_dealloc;
	OZ_vtable_init[OZ_CLASS_OZObject] = (OZ_fn_init)OZObject_init;
	OZ_vtable_init[OZ_CLASS_OZLed] = (OZ_fn_init)OZLed_init;
	OZ_vtable_toggle[OZ_CLASS_OZLed] = (OZ_fn_toggle)OZLed_toggle;
}

void OZObject_dispatch_free(struct OZObject *obj)
{
	switch (obj->oz_class_id) {
	case OZ_CLASS_OZObject: OZObject_free((struct OZObject *)obj); break;
	case OZ_CLASS_OZLed: OZLed_free((struct OZLed *)obj); break;
	default: break;
	}
}
