/* Auto-generated by oz_transpile -- do not edit */
#include "OZBlinky_ozh.h"
#include "OZObject_ozh.h"

OZ_SLAB_DEFINE(oz_slab_OZBlinky, sizeof(struct OZBlinky), 1, 4);
/* Copyright 2024 Rodrigo Peixoto */

#include <zephyr/kernel.h>
/* @interface OZBlinky — see OZBlinky_ozh.h */
/* @implementation OZBlinky */

/* Initialize the blinky LED */

/* -[OZBlinky initWithPin:] */
struct OZBlinky * OZBlinky_initWithPin_(struct OZBlinky *self, int pin)
{
	self = OZObject_init((struct OZObject *)self);
	if (self) {
		self->_pin = pin;
	}
	return self;
}

/* Toggle the LED state */

/* -[OZBlinky toggle] */
void OZBlinky_toggle(struct OZBlinky *self)
{
}

void OZBlinky_dealloc(struct OZBlinky *self)
{
	OZObject_dealloc((struct OZObject *)self);
}


/* @end OZBlinky */
