/* Auto-generated by oz_transpile -- do not edit */
#include "Animal_ozh.h"
#include "oz_mem_slabs.h"

void Animal_speak(struct Animal *self)
{
}
int Animal_legs(struct Animal *self)
{
	return self->_legs;
}
void Animal_dealloc(struct Animal *self)
{
	OZObject_dealloc((struct OZObject *)self);
}
