/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "platform/oz_platform.h"
#include "oz_dispatch.h"
#include <string.h>
#include "OZObject_ozh.h"

struct Animal {
	struct OZObject base;
	int _legs;
};

void Animal_speak(struct Animal *self);
int Animal_legs(struct Animal *self);
void Animal_dealloc(struct Animal *self);

extern oz_slab_t oz_slab_Animal;

static inline struct Animal *Animal_alloc(void)
{
	struct Animal *obj;
	if (oz_slab_alloc(&oz_slab_Animal, (void **)&obj) != 0) {
		return (struct Animal *)0;
	}
	memset(obj, 0, sizeof(struct Animal));
	obj->base.oz_class_id = OZ_CLASS_Animal;
	oz_atomic_init(&obj->base._refcount, 1);
	return obj;
}

static inline void Animal_free(struct Animal *obj)
{
	oz_slab_free(&oz_slab_Animal, (void *)obj);
}
