/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "oz/platform/oz_platform.h"
#include "oz_dispatch.h"
#include "OZObject.h"

struct Animal {
	struct OZObject base;
	int _legs;
};

void Animal_speak(struct Animal *self);
int Animal_legs(struct Animal *self);
void Animal_dealloc(struct Animal *self);

