/* Auto-generated by oz_transpile -- do not edit */
#include "Animal_ozh.h"
#include "Dog_ozh.h"
#include "OZObject_ozh.h"

OZ_SLAB_DEFINE(oz_slab_Animal, sizeof(struct Animal), 1, 4);

void Animal_speak(struct Animal *self)
{
}
int Animal_legs(struct Animal *self)
{
	return self->_legs;
}
void Animal_dealloc(struct Animal *self)
{
	OZObject_dealloc((struct OZObject *)self);
}
