/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "platform/oz_platform.h"
#include "oz_dispatch.h"
#include "Animal.h"

struct Dog {
	struct Animal base;
	int _name;
};

void Dog_fetch(struct Dog *self);
void Dog_dealloc(struct Dog *self);

