/* Auto-generated by oz_transpile -- do not edit */
#include "Dog.h"
#include "oz_mem_slabs.h"

void Dog_fetch(struct Dog *self)
{
}
void Dog_dealloc(struct Dog *self)
{
	Animal_dealloc((struct Animal *)self);
}
