/* Auto-generated by oz_transpile -- do not edit */
#include "Dog_ozh.h"
#include "Animal_ozh.h"
#include "OZObject_ozh.h"

OZ_SLAB_DEFINE(oz_slab_Dog, sizeof(struct Dog), 1, 4);

void Dog_fetch(struct Dog *self)
{
}
void Dog_dealloc(struct Dog *self)
{
	Animal_dealloc((struct Animal *)self);
}
