/* Auto-generated by oz_transpile -- do not edit */
#include "oz_dispatch.h"
#include "OZObject_ozh.h"
#include "Animal_ozh.h"
#include "Dog_ozh.h"

const char *const oz_class_names[OZ_CLASS_COUNT] = {
	[OZ_CLASS_OZObject] = "OZObject",
	[OZ_CLASS_Animal] = "Animal",
	[OZ_CLASS_Dog] = "Dog",
};

const uint8_t oz_superclass_id[OZ_CLASS_COUNT] = {
	[OZ_CLASS_OZObject] = OZ_CLASS_COUNT,
	[OZ_CLASS_Animal] = OZ_CLASS_OZObject,
	[OZ_CLASS_Dog] = OZ_CLASS_Animal,
};

OZ_fn_dealloc OZ_vtable_dealloc[OZ_CLASS_COUNT];
OZ_fn_init OZ_vtable_init[OZ_CLASS_COUNT];

__attribute__((constructor))
static void oz_register_vtables(void)
{
	OZ_vtable_dealloc[OZ_CLASS_OZObject] = (OZ_fn_dealloc)OZObject_dealloc;
	OZ_vtable_dealloc[OZ_CLASS_Animal] = (OZ_fn_dealloc)Animal_dealloc;
	OZ_vtable_dealloc[OZ_CLASS_Dog] = (OZ_fn_dealloc)Dog_dealloc;
	OZ_vtable_init[OZ_CLASS_OZObject] = (OZ_fn_init)OZObject_init;
	OZ_vtable_init[OZ_CLASS_Animal] = (OZ_fn_init)OZObject_init;
	OZ_vtable_init[OZ_CLASS_Dog] = (OZ_fn_init)OZObject_init;
}
