/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "oz/platform/oz_platform.h"
#include <string.h>

#include "OZObject.h"
#include "Animal.h"
#include "Dog.h"

extern oz_slab_t oz_slab_OZObject;
extern oz_slab_t oz_slab_Animal;
extern oz_slab_t oz_slab_Dog;

static inline struct OZObject *OZObject_alloc(void)
{
	struct OZObject *obj;
	if (oz_slab_alloc(&oz_slab_OZObject, (void **)&obj) != 0) {
		return (struct OZObject *)0;
	}
	memset(obj, 0, sizeof(struct OZObject));
	obj->oz_class_id = OZ_CLASS_OZObject;
	oz_atomic_init(&obj->_refcount, 1);
	return obj;
}

static inline void OZObject_free(struct OZObject *obj)
{
	oz_slab_free(&oz_slab_OZObject, (void *)obj);
}

static inline struct Animal *Animal_alloc(void)
{
	struct Animal *obj;
	if (oz_slab_alloc(&oz_slab_Animal, (void **)&obj) != 0) {
		return (struct Animal *)0;
	}
	memset(obj, 0, sizeof(struct Animal));
	obj->base.oz_class_id = OZ_CLASS_Animal;
	oz_atomic_init(&obj->base._refcount, 1);
	return obj;
}

static inline void Animal_free(struct Animal *obj)
{
	oz_slab_free(&oz_slab_Animal, (void *)obj);
}

static inline struct Dog *Dog_alloc(void)
{
	struct Dog *obj;
	if (oz_slab_alloc(&oz_slab_Dog, (void **)&obj) != 0) {
		return (struct Dog *)0;
	}
	memset(obj, 0, sizeof(struct Dog));
	obj->base.base.oz_class_id = OZ_CLASS_Dog;
	oz_atomic_init(&obj->base.base._refcount, 1);
	return obj;
}

static inline void Dog_free(struct Dog *obj)
{
	oz_slab_free(&oz_slab_Dog, (void *)obj);
}

static inline void OZObject_dispatch_free(struct OZObject *obj)
{
	switch (obj->oz_class_id) {
	case OZ_CLASS_OZObject: OZObject_free((struct OZObject *)obj); break;
	case OZ_CLASS_Animal: Animal_free((struct Animal *)obj); break;
	case OZ_CLASS_Dog: Dog_free((struct Dog *)obj); break;
	default: break;
	}
}

