/* Auto-generated by oz_transpile -- do not edit */
#include "oz_mem_slabs.h"

OZ_SLAB_DEFINE(oz_slab_OZObject, sizeof(struct OZObject), 1, 4);
OZ_SLAB_DEFINE(oz_slab_Animal, sizeof(struct Animal), 1, 4);
OZ_SLAB_DEFINE(oz_slab_Dog, sizeof(struct Dog), 1, 4);
