/* Auto-generated by oz_transpile -- do not edit */
#include "Controller_ozh.h"
#include "oz_mem_slabs.h"

void Controller_setSensor_(struct Controller *self, struct Sensor * s)
{
	OZObject_retain((struct OZObject *)s);
	OZObject_retain((struct OZObject *)s);
	OZObject_release((struct OZObject *)self->_sensor);
	self->_sensor = s;
	OZObject_release((struct OZObject *)s);
}
void Controller_dealloc(struct Controller *self)
{
	OZObject_release((struct OZObject *)self->_sensor);
	OZObject_dealloc((struct OZObject *)self);
}
