/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "oz/platform/oz_platform.h"
#include "oz_dispatch.h"
#include "OZObject.h"

struct Controller {
	struct OZObject base;
	struct Sensor * _sensor;
	int _count;
};

void Controller_setSensor_(struct Controller *self, struct Sensor * s);
void Controller_dealloc(struct Controller *self);

