/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "platform/oz_platform.h"
#include <string.h>

#include "OZObject.h"
#include "Controller.h"
#include "Sensor.h"

extern oz_slab_t oz_slab_OZObject;
extern oz_slab_t oz_slab_Controller;
extern oz_slab_t oz_slab_Sensor;

static inline struct OZObject *OZObject_alloc(void)
{
	struct OZObject *obj;
	if (oz_slab_alloc(&oz_slab_OZObject, (void **)&obj) != 0) {
		return (struct OZObject *)0;
	}
	memset(obj, 0, sizeof(struct OZObject));
	obj->oz_class_id = OZ_CLASS_OZObject;
	oz_atomic_init(&obj->_refcount, 1);
	return obj;
}

static inline void OZObject_free(struct OZObject *obj)
{
	oz_slab_free(&oz_slab_OZObject, (void *)obj);
}

static inline struct Controller *Controller_alloc(void)
{
	struct Controller *obj;
	if (oz_slab_alloc(&oz_slab_Controller, (void **)&obj) != 0) {
		return (struct Controller *)0;
	}
	memset(obj, 0, sizeof(struct Controller));
	obj->base.oz_class_id = OZ_CLASS_Controller;
	oz_atomic_init(&obj->base._refcount, 1);
	return obj;
}

static inline void Controller_free(struct Controller *obj)
{
	oz_slab_free(&oz_slab_Controller, (void *)obj);
}

static inline struct Sensor *Sensor_alloc(void)
{
	struct Sensor *obj;
	if (oz_slab_alloc(&oz_slab_Sensor, (void **)&obj) != 0) {
		return (struct Sensor *)0;
	}
	memset(obj, 0, sizeof(struct Sensor));
	obj->base.oz_class_id = OZ_CLASS_Sensor;
	oz_atomic_init(&obj->base._refcount, 1);
	return obj;
}

static inline void Sensor_free(struct Sensor *obj)
{
	oz_slab_free(&oz_slab_Sensor, (void *)obj);
}

static inline void OZObject_dispatch_free(struct OZObject *obj)
{
	switch (obj->oz_class_id) {
	case OZ_CLASS_OZObject: OZObject_free((struct OZObject *)obj); break;
	case OZ_CLASS_Controller: Controller_free((struct Controller *)obj); break;
	case OZ_CLASS_Sensor: Sensor_free((struct Sensor *)obj); break;
	default: break;
	}
}

