/* Auto-generated by oz_transpile -- do not edit */
#include "Sensor_ozh.h"
#include "Controller_ozh.h"
#include "OZObject_ozh.h"

OZ_SLAB_DEFINE(oz_slab_Sensor, sizeof(struct Sensor), 1, 4);

int Sensor_value(struct Sensor *self)
{
	return self->_value;
}
void Sensor_dealloc(struct Sensor *self)
{
	OZObject_dealloc((struct OZObject *)self);
}
