/* Auto-generated by oz_transpile -- do not edit */
#include "Sensor_ozh.h"
#include "oz_mem_slabs.h"

int Sensor_value(struct Sensor *self)
{
	return self->_value;
}
void Sensor_dealloc(struct Sensor *self)
{
	OZObject_dealloc((struct OZObject *)self);
}
