/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "platform/oz_platform.h"
#include "oz_dispatch.h"
#include "OZObject.h"

struct Sensor {
	struct OZObject base;
	int _value;
};

int Sensor_value(struct Sensor *self);
void Sensor_dealloc(struct Sensor *self);

