// SPDX-License-Identifier: Apache-2.0
//
// companion.rs - the one small generated file for multi-implementor
// dispatch (dealloc's const-vtable, computed entirely at compile time and
// never mutated at runtime) and pool/init registration, mirroring the
// existing oz_dispatch.h/.c pattern used by the Python pipeline.
//
// Only the root class's full struct lives here, because oz_static_retain/
// oz_static_release/the dealloc switch are generic (shared by every
// class) and need its tracking fields (oz_class_id, oz_refcount,
// oz_deallocating) directly -- mirroring how the Python pipeline already
// treats OZObject as the Foundation root's own generated pair. Every
// other class's full struct (and alloc/free, which need it for sizeof)
// lives in-place at its own @interface/@implementation; this file only
// forward-declares them, which is all its dealloc-dispatch switch needs
// (it only casts pointers and calls functions through them, never
// dereferences).
//
// Everything here is grouped and labeled per originating class, so a
// reader sees "here's what each class contributed to shared infra," not
// an undifferentiated dump.

use crate::model::Program;

fn find_defining_dealloc(program: &Program, start: &str) -> Option<String> {
    let mut cur = Some(start.to_string());
    while let Some(name) = cur {
        let info = program.classes.get(&name)?;
        if info.methods.iter().any(|m| !m.is_class_method && m.selector == "dealloc") {
            return Some(name);
        }
        cur = info.superclass.clone();
    }
    None
}

/// Order classes so a superclass's struct always precedes its subclasses'
/// (C requires a struct's members to be complete types when embedded by
/// value, e.g. `struct Base base;`), regardless of the order they appeared
/// in the source file.
fn topological_order(program: &Program) -> Vec<String> {
    let mut order = Vec::new();
    let mut visited = std::collections::HashSet::new();
    fn visit(
        program: &Program,
        name: &str,
        visited: &mut std::collections::HashSet<String>,
        order: &mut Vec<String>,
    ) {
        if !visited.insert(name.to_string()) {
            return;
        }
        if let Some(sup) = program.classes.get(name).and_then(|c| c.superclass.clone()) {
            visit(program, &sup, visited, order);
        }
        order.push(name.to_string());
    }
    for name in &program.class_order {
        visit(program, name, &mut visited, &mut order);
    }
    order
}

/// `{name}_oz_alloc`/`{name}_oz_free`: malloc-based (host-testable; not
/// slab-integrated -- this crate isn't wired into the embedded build
/// yet). `root` is whichever class has no superclass; alloc always needs
/// it to set the tracking fields regardless of which class is being
/// allocated.
pub(crate) fn render_alloc_free(name: &str, root: &str) -> String {
    let mut c = String::new();
    c.push_str(&format!("struct {name} *{name}_oz_alloc(void)\n{{\n", name = name));
    c.push_str(&format!(
        "\tstruct {name} *obj = malloc(sizeof(struct {name}));\n\
         \tif (!obj) {{\n\t\treturn (struct {name} *)0;\n\t}}\n\
         \tmemset(obj, 0, sizeof(struct {name}));\n",
        name = name
    ));
    c.push_str(&format!(
        "\t((struct {root} *)obj)->oz_class_id = OZ_STATIC_CLASS_{name};\n\
         \toz_atomic_init(&((struct {root} *)obj)->oz_refcount, 1);\n",
        root = root,
        name = name
    ));
    c.push_str(&format!(
        "\treturn obj;\n}}\n\nvoid {name}_oz_free(struct {name} *obj)\n{{\n\tfree(obj);\n}}\n\n",
        name = name
    ));
    c
}

fn class_label(program: &Program, name: &str, id: usize) -> String {
    match &program.classes[name].superclass {
        Some(sup) => format!("-- {} (id {}, extends {}) --", name, id, sup),
        None => format!("-- {} (id {}, root) --", name, id),
    }
}

pub fn render(
    program: &Program,
    hoisted_blocks: &[String],
    hoisted_structs: &[(String, String)],
) -> (String, String) {
    let root = program.root_class().map(|s| s.to_string());
    // The root class always terminates the [super dealloc] chain. If the
    // user didn't write one, synthesize a no-op so every subclass's chain
    // still resolves statically.
    let root_needs_synthetic_dealloc =
        root.as_deref().is_some_and(|r| find_defining_dealloc(program, r).is_none());
    let struct_order = topological_order(program);
    let struct_text: std::collections::HashMap<&str, &str> =
        hoisted_structs.iter().map(|(n, t)| (n.as_str(), t.as_str())).collect();

    let mut h = String::new();
    h.push_str("/* Auto-generated by oz_static -- do not edit */\n#pragma once\n\n");
    h.push_str("#include \"platform/oz_platform.h\"\n#include <stdlib.h>\n#include <string.h>\n\n");

    // One labeled section per class: its id, its struct (full for root,
    // forward-declared otherwise), its method prototypes (needed here so
    // the dealloc-dispatch switch below can call them across the
    // translation-unit boundary), and its alloc/free prototypes.
    for name in &struct_order {
        let id = program.class_id(name).unwrap_or(0);
        h.push_str(&format!("/* {} */\n", class_label(program, name, id)));
        h.push_str(&format!("#define OZ_STATIC_CLASS_{} {}\n", name, id));
        match struct_text.get(name.as_str()) {
            Some(text) => h.push_str(text),
            None => h.push_str(&format!("struct {};\n", name)),
        }
        for m in &program.classes[name].methods {
            h.push_str(&crate::emit::render_prototype(name, m));
        }
        h.push_str(&format!(
            "struct {name} *{name}_oz_alloc(void);\nvoid {name}_oz_free(struct {name} *obj);\n",
            name = name
        ));
        if root.as_deref() == Some(name.as_str()) {
            h.push_str(&format!(
                "struct {root} *oz_static_retain(struct {root} *self);\n\
                 void oz_static_release(struct {root} *self);\n",
                root = name
            ));
            if root_needs_synthetic_dealloc {
                h.push_str(&format!("void {root}_dealloc(struct {root} *self);\n", root = name));
            }
        }
        h.push('\n');
    }

    let mut c = String::new();
    c.push_str("/* Auto-generated by oz_static -- do not edit */\n#include \"oz_static_dispatch.h\"\n\n");

    if let Some(root) = &root {
        c.push_str(&format!("/* {} (root): alloc/free */\n", root));
        c.push_str(&render_alloc_free(root, root));

        if root_needs_synthetic_dealloc {
            c.push_str(&format!(
                "/* {root}: no -dealloc in source -- synthesized as a no-op so\n\
                 * every subclass's [super dealloc] chain still resolves statically */\n\
                 void {root}_dealloc(struct {root} *self)\n{{\n\t(void)self;\n}}\n\n",
                root = root
            ));
        }

        c.push_str("/* generic refcounting -- shared by every class, not tied to one */\n");
        c.push_str(&format!(
            "struct {root} *oz_static_retain(struct {root} *self)\n{{\n\
             \tif (self) {{\n\t\toz_atomic_inc(&self->oz_refcount);\n\t}}\n\treturn self;\n}}\n\n",
            root = root
        ));

        c.push_str(
            "/* dealloc dispatch: the one virtual call this design needs. Resolved\n\
             * entirely at compile time via this class_id switch (the \"const\n\
             * vtable\") -- never mutated at runtime. */\n",
        );
        c.push_str(&format!(
            "void oz_static_release(struct {root} *self)\n{{\n\
             \tif (!self) {{\n\t\treturn;\n\t}}\n\
             \tif (!oz_atomic_dec_and_test(&self->oz_refcount)) {{\n\t\treturn;\n\t}}\n\
             \tif (self->oz_deallocating) {{\n\t\treturn;\n\t}}\n\
             \tself->oz_deallocating = 1;\n\
             \tswitch (self->oz_class_id) {{\n",
            root = root
        ));
        for name in &program.class_order {
            let defining =
                find_defining_dealloc(program, name).unwrap_or_else(|| root.clone());
            c.push_str(&format!("\tcase OZ_STATIC_CLASS_{}: /* {} */\n", name, name));
            c.push_str(&format!("\t\t{}_dealloc((struct {} *)self);\n", defining, defining));
            c.push_str(&format!("\t\t{}_oz_free((struct {} *)self);\n\t\tbreak;\n", name, name));
        }
        c.push_str("\tdefault:\n\t\tbreak;\n\t}\n}\n\n");
    }

    for name in &program.class_order {
        if program.classes[name].has_class_initialize {
            c.push_str(&format!(
                "/* {name}: +initialize registration (runs once, before main()) */\n\
                 OZ_AUTO_INIT({name}_oz_auto_init, {name}_initialize_cls);\n\n",
                name = name
            ));
        }
    }

    if !hoisted_blocks.is_empty() {
        c.push_str("/* non-capturing blocks, hoisted to static functions */\n");
        for b in hoisted_blocks {
            c.push_str(b);
            c.push('\n');
        }
    }

    (h, c)
}
