// SPDX-License-Identifier: Apache-2.0
//
// companion.rs - the one small generated file for multi-implementor
// dispatch (dealloc's const-vtable, computed entirely at compile time and
// never mutated at runtime) and pool/init registration, mirroring the
// existing oz_dispatch.h/.c pattern used by the Python pipeline.

use crate::model::Program;

fn find_defining_dealloc(program: &Program, start: &str) -> Option<String> {
    let mut cur = Some(start.to_string());
    while let Some(name) = cur {
        let info = program.classes.get(&name)?;
        if info.methods.iter().any(|m| !m.is_class_method && m.selector == "dealloc") {
            return Some(name);
        }
        cur = info.superclass.clone();
    }
    None
}

/// Order classes so a superclass's struct always precedes its subclasses'
/// (C requires a struct's members to be complete types when embedded by
/// value, e.g. `struct Base base;`), regardless of the order they appeared
/// in the source file.
fn topological_order(program: &Program) -> Vec<String> {
    let mut order = Vec::new();
    let mut visited = std::collections::HashSet::new();
    fn visit(
        program: &Program,
        name: &str,
        visited: &mut std::collections::HashSet<String>,
        order: &mut Vec<String>,
    ) {
        if !visited.insert(name.to_string()) {
            return;
        }
        if let Some(sup) = program.classes.get(name).and_then(|c| c.superclass.clone()) {
            visit(program, &sup, visited, order);
        }
        order.push(name.to_string());
    }
    for name in &program.class_order {
        visit(program, name, &mut visited, &mut order);
    }
    order
}

pub fn render(
    program: &Program,
    hoisted_blocks: &[String],
    hoisted_structs: &[(String, String)],
) -> (String, String) {
    let root = program.root_class().map(|s| s.to_string());
    // The root class always terminates the [super dealloc] chain. If the
    // user didn't write one, synthesize a no-op so every subclass's chain
    // still resolves statically.
    let root_needs_synthetic_dealloc =
        root.as_deref().is_some_and(|r| find_defining_dealloc(program, r).is_none());
    let struct_order = topological_order(program);
    let struct_text: std::collections::HashMap<&str, &str> =
        hoisted_structs.iter().map(|(n, t)| (n.as_str(), t.as_str())).collect();

    let mut h = String::new();
    h.push_str("/* Auto-generated by oz_static -- do not edit */\n#pragma once\n\n");
    h.push_str("#include \"platform/oz_platform.h\"\n\n");
    for (i, name) in program.class_order.iter().enumerate() {
        h.push_str(&format!("#define OZ_STATIC_CLASS_{} {}\n", name, i));
    }
    h.push('\n');
    for name in &struct_order {
        if let Some(text) = struct_text.get(name.as_str()) {
            h.push_str(text);
            h.push('\n');
        }
    }
    // Method prototypes also go here (not only in-place at the interface):
    // oz_static_release's const-vtable dispatch (in this same file) needs
    // to call every class's `dealloc` directly, so it must see the
    // prototype regardless of translation-unit boundaries. The in-place
    // output additionally repeats these at their original interface
    // location for readability; duplicate matching prototypes are valid C.
    for name in &program.class_order {
        for m in &program.classes[name].methods {
            h.push_str(&crate::emit::render_prototype(name, m));
        }
    }
    if let Some(root) = &root {
        h.push_str(&format!(
            "\nstruct {root} *oz_static_retain(struct {root} *self);\n\
             void oz_static_release(struct {root} *self);\n",
            root = root
        ));
        if root_needs_synthetic_dealloc {
            h.push_str(&format!("void {root}_dealloc(struct {root} *self);\n", root = root));
        }
    }
    for name in &program.class_order {
        h.push_str(&format!(
            "struct {name} *{name}_oz_alloc(void);\nvoid {name}_oz_free(struct {name} *obj);\n",
            name = name
        ));
    }

    let mut c = String::new();
    c.push_str(
        "/* Auto-generated by oz_static -- do not edit */\n#include \"oz_static_dispatch.h\"\n#include <stdlib.h>\n#include <string.h>\n\n",
    );

    for name in &program.class_order {
        c.push_str(&format!("struct {name} *{name}_oz_alloc(void)\n{{\n", name = name));
        c.push_str(&format!(
            "\tstruct {name} *obj = malloc(sizeof(struct {name}));\n\
             \tif (!obj) {{\n\t\treturn (struct {name} *)0;\n\t}}\n\
             \tmemset(obj, 0, sizeof(struct {name}));\n",
            name = name
        ));
        if let Some(root) = &root {
            c.push_str(&format!(
                "\t((struct {root} *)obj)->oz_class_id = OZ_STATIC_CLASS_{name};\n\
                 \toz_atomic_init(&((struct {root} *)obj)->oz_refcount, 1);\n",
                root = root,
                name = name
            ));
        }
        c.push_str(&format!(
            "\treturn obj;\n}}\n\nvoid {name}_oz_free(struct {name} *obj)\n{{\n\tfree(obj);\n}}\n\n",
            name = name
        ));
    }

    if let Some(root) = &root {
        if root_needs_synthetic_dealloc {
            c.push_str(&format!(
                "void {root}_dealloc(struct {root} *self)\n{{\n\t(void)self;\n}}\n\n",
                root = root
            ));
        }

        c.push_str(&format!(
            "struct {root} *oz_static_retain(struct {root} *self)\n{{\n\
             \tif (self) {{\n\t\toz_atomic_inc(&self->oz_refcount);\n\t}}\n\treturn self;\n}}\n\n",
            root = root
        ));

        c.push_str(&format!(
            "void oz_static_release(struct {root} *self)\n{{\n\
             \tif (!self) {{\n\t\treturn;\n\t}}\n\
             \tif (!oz_atomic_dec_and_test(&self->oz_refcount)) {{\n\t\treturn;\n\t}}\n\
             \tif (self->oz_deallocating) {{\n\t\treturn;\n\t}}\n\
             \tself->oz_deallocating = 1;\n\
             \tswitch (self->oz_class_id) {{\n",
            root = root
        ));
        for name in &program.class_order {
            let defining =
                find_defining_dealloc(program, name).unwrap_or_else(|| root.clone());
            c.push_str(&format!("\tcase OZ_STATIC_CLASS_{}:\n", name));
            c.push_str(&format!("\t\t{}_dealloc((struct {} *)self);\n", defining, defining));
            c.push_str(&format!("\t\t{}_oz_free((struct {} *)self);\n\t\tbreak;\n", name, name));
        }
        c.push_str("\tdefault:\n\t\tbreak;\n\t}\n}\n\n");
    }

    for name in &program.class_order {
        if program.classes[name].has_class_initialize {
            c.push_str(&format!(
                "OZ_AUTO_INIT({name}_oz_auto_init, {name}_initialize_cls);\n",
                name = name
            ));
        }
    }

    if !hoisted_blocks.is_empty() {
        c.push('\n');
        for b in hoisted_blocks {
            c.push_str(b);
            c.push('\n');
        }
    }

    (h, c)
}
