/* Auto-generated by oz_transpile -- do not edit */
#include "Circle_ozh.h"
#include "OZObject_ozh.h"
#include "Square_ozh.h"

OZ_SLAB_DEFINE(oz_slab_Circle, sizeof(struct Circle), 1, 4);

void Circle_draw(struct Circle *self)
{
}
int Circle_color(struct Circle *self)
{
	return 1;
}
void Circle_dealloc(struct Circle *self)
{
	OZObject_dealloc((struct OZObject *)self);
}
