/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "oz/platform/oz_platform.h"
#include "oz_dispatch.h"
#include "OZObject.h"

struct Circle {
	struct OZObject base;
	int _radius;
};

void Circle_draw(struct Circle *self);
int Circle_color(struct Circle *self);
void Circle_dealloc(struct Circle *self);

