/* Auto-generated by oz_transpile -- do not edit */
#include "Circle.h"
#include "oz_mem_slabs.h"

void Circle_draw(struct Circle *self)
{
}
int Circle_color(struct Circle *self)
{
	return 1;
}
void Circle_dealloc(struct Circle *self)
{
	OZObject_dealloc((struct OZObject *)self);
}
