/* Auto-generated by oz_transpile -- do not edit */
#include "oz_dispatch.h"
#include "OZObject_ozh.h"
#include "Circle_ozh.h"
#include "Square_ozh.h"

const char *const oz_class_names[OZ_CLASS_COUNT] = {
	[OZ_CLASS_OZObject] = "OZObject",
	[OZ_CLASS_Circle] = "Circle",
	[OZ_CLASS_Square] = "Square",
};

const uint8_t oz_superclass_id[OZ_CLASS_COUNT] = {
	[OZ_CLASS_OZObject] = OZ_CLASS_COUNT,
	[OZ_CLASS_Circle] = OZ_CLASS_OZObject,
	[OZ_CLASS_Square] = OZ_CLASS_OZObject,
};

OZ_fn_color OZ_vtable_color[OZ_CLASS_COUNT];
OZ_fn_dealloc OZ_vtable_dealloc[OZ_CLASS_COUNT];
OZ_fn_draw OZ_vtable_draw[OZ_CLASS_COUNT];
OZ_fn_init OZ_vtable_init[OZ_CLASS_COUNT];

__attribute__((constructor))
static void oz_register_vtables(void)
{
	OZ_vtable_color[OZ_CLASS_Circle] = (OZ_fn_color)Circle_color;
	OZ_vtable_color[OZ_CLASS_Square] = (OZ_fn_color)Square_color;
	OZ_vtable_dealloc[OZ_CLASS_OZObject] = (OZ_fn_dealloc)OZObject_dealloc;
	OZ_vtable_dealloc[OZ_CLASS_Circle] = (OZ_fn_dealloc)Circle_dealloc;
	OZ_vtable_dealloc[OZ_CLASS_Square] = (OZ_fn_dealloc)Square_dealloc;
	OZ_vtable_draw[OZ_CLASS_Circle] = (OZ_fn_draw)Circle_draw;
	OZ_vtable_draw[OZ_CLASS_Square] = (OZ_fn_draw)Square_draw;
	OZ_vtable_init[OZ_CLASS_OZObject] = (OZ_fn_init)OZObject_init;
	OZ_vtable_init[OZ_CLASS_Circle] = (OZ_fn_init)OZObject_init;
	OZ_vtable_init[OZ_CLASS_Square] = (OZ_fn_init)OZObject_init;
}
