/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "oz/platform/oz_platform.h"
#include <string.h>

#include "OZObject.h"
#include "Circle.h"
#include "Square.h"

extern oz_slab_t oz_slab_OZObject;
extern oz_slab_t oz_slab_Circle;
extern oz_slab_t oz_slab_Square;

static inline struct OZObject *OZObject_alloc(void)
{
	struct OZObject *obj;
	if (oz_slab_alloc(&oz_slab_OZObject, (void **)&obj) != 0) {
		return (struct OZObject *)0;
	}
	memset(obj, 0, sizeof(struct OZObject));
	obj->oz_class_id = OZ_CLASS_OZObject;
	oz_atomic_init(&obj->_refcount, 1);
	return obj;
}

static inline void OZObject_free(struct OZObject *obj)
{
	oz_slab_free(&oz_slab_OZObject, (void *)obj);
}

static inline struct Circle *Circle_alloc(void)
{
	struct Circle *obj;
	if (oz_slab_alloc(&oz_slab_Circle, (void **)&obj) != 0) {
		return (struct Circle *)0;
	}
	memset(obj, 0, sizeof(struct Circle));
	obj->base.oz_class_id = OZ_CLASS_Circle;
	oz_atomic_init(&obj->base._refcount, 1);
	return obj;
}

static inline void Circle_free(struct Circle *obj)
{
	oz_slab_free(&oz_slab_Circle, (void *)obj);
}

static inline struct Square *Square_alloc(void)
{
	struct Square *obj;
	if (oz_slab_alloc(&oz_slab_Square, (void **)&obj) != 0) {
		return (struct Square *)0;
	}
	memset(obj, 0, sizeof(struct Square));
	obj->base.oz_class_id = OZ_CLASS_Square;
	oz_atomic_init(&obj->base._refcount, 1);
	return obj;
}

static inline void Square_free(struct Square *obj)
{
	oz_slab_free(&oz_slab_Square, (void *)obj);
}

static inline void OZObject_dispatch_free(struct OZObject *obj)
{
	switch (obj->oz_class_id) {
	case OZ_CLASS_OZObject: OZObject_free((struct OZObject *)obj); break;
	case OZ_CLASS_Circle: Circle_free((struct Circle *)obj); break;
	case OZ_CLASS_Square: Square_free((struct Square *)obj); break;
	default: break;
	}
}

