/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "platform/oz_platform.h"
#include "oz_dispatch.h"
#include "OZObject.h"

struct Square {
	struct OZObject base;
	int _side;
};

void Square_draw(struct Square *self);
int Square_color(struct Square *self);
void Square_dealloc(struct Square *self);

