/* Auto-generated by oz_transpile -- do not edit */
#include "Square_ozh.h"
#include "Circle_ozh.h"
#include "OZObject_ozh.h"

OZ_SLAB_DEFINE(oz_slab_Square, sizeof(struct Square), 1, 4);

void Square_draw(struct Square *self)
{
}
int Square_color(struct Square *self)
{
	return 2;
}
void Square_dealloc(struct Square *self)
{
	OZObject_dealloc((struct OZObject *)self);
}
