/* Auto-generated by oz_transpile -- do not edit */
#include "Square_ozh.h"
#include "oz_mem_slabs.h"

void Square_draw(struct Square *self)
{
}
int Square_color(struct Square *self)
{
	return 2;
}
void Square_dealloc(struct Square *self)
{
	OZObject_dealloc((struct OZObject *)self);
}
