/* Auto-generated by oz_transpile -- do not edit */
#include "Logger.h"
#include "oz_mem_slabs.h"

void Logger_log(struct Logger *self)
{
}
void Logger_dealloc(struct Logger *self)
{
	OZObject_dealloc((struct OZObject *)self);
}
