/* Auto-generated by oz_transpile -- do not edit */
#include "Logger_ozh.h"
#include "OZObject_ozh.h"
#include "Timer_ozh.h"

OZ_SLAB_DEFINE(oz_slab_Logger, sizeof(struct Logger), 1, 4);

void Logger_log(struct Logger *self)
{
}
void Logger_dealloc(struct Logger *self)
{
	OZObject_dealloc((struct OZObject *)self);
}
