/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "platform/oz_platform.h"
#include "oz_dispatch.h"
#include "OZObject_ozh.h"

struct Logger {
	struct OZObject base;
	int _level;
};

void Logger_log(struct Logger *self);
void Logger_dealloc(struct Logger *self);

