/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "platform/oz_platform.h"
#include <string.h>

#include "OZObject.h"
#include "Logger.h"
#include "Timer.h"

extern oz_slab_t oz_slab_OZObject;
extern oz_slab_t oz_slab_Logger;
extern oz_slab_t oz_slab_Timer;

static inline struct OZObject *OZObject_alloc(void)
{
	struct OZObject *obj;
	if (oz_slab_alloc(&oz_slab_OZObject, (void **)&obj) != 0) {
		return (struct OZObject *)0;
	}
	memset(obj, 0, sizeof(struct OZObject));
	obj->oz_class_id = OZ_CLASS_OZObject;
	oz_atomic_init(&obj->_refcount, 1);
	return obj;
}

static inline void OZObject_free(struct OZObject *obj)
{
	oz_slab_free(&oz_slab_OZObject, (void *)obj);
}

static inline struct Logger *Logger_alloc(void)
{
	struct Logger *obj;
	if (oz_slab_alloc(&oz_slab_Logger, (void **)&obj) != 0) {
		return (struct Logger *)0;
	}
	memset(obj, 0, sizeof(struct Logger));
	obj->base.oz_class_id = OZ_CLASS_Logger;
	oz_atomic_init(&obj->base._refcount, 1);
	return obj;
}

static inline void Logger_free(struct Logger *obj)
{
	oz_slab_free(&oz_slab_Logger, (void *)obj);
}

static inline struct Timer *Timer_alloc(void)
{
	struct Timer *obj;
	if (oz_slab_alloc(&oz_slab_Timer, (void **)&obj) != 0) {
		return (struct Timer *)0;
	}
	memset(obj, 0, sizeof(struct Timer));
	obj->base.oz_class_id = OZ_CLASS_Timer;
	oz_atomic_init(&obj->base._refcount, 1);
	return obj;
}

static inline void Timer_free(struct Timer *obj)
{
	oz_slab_free(&oz_slab_Timer, (void *)obj);
}

static inline void OZObject_dispatch_free(struct OZObject *obj)
{
	switch (obj->oz_class_id) {
	case OZ_CLASS_OZObject: OZObject_free((struct OZObject *)obj); break;
	case OZ_CLASS_Logger: Logger_free((struct Logger *)obj); break;
	case OZ_CLASS_Timer: Timer_free((struct Timer *)obj); break;
	default: break;
	}
}

