/* Auto-generated by oz_transpile -- do not edit */
#include "Timer.h"
#include "oz_mem_slabs.h"

void Timer_start(struct Timer *self)
{
}
void Timer_stop(struct Timer *self)
{
}
void Timer_dealloc(struct Timer *self)
{
	OZObject_dealloc((struct OZObject *)self);
}
