/* Auto-generated by oz_transpile -- do not edit */
#include "Timer_ozh.h"
#include "Logger_ozh.h"
#include "OZObject_ozh.h"

OZ_SLAB_DEFINE(oz_slab_Timer, sizeof(struct Timer), 1, 4);

void Timer_start(struct Timer *self)
{
}
void Timer_stop(struct Timer *self)
{
}
void Timer_dealloc(struct Timer *self)
{
	OZObject_dealloc((struct OZObject *)self);
}
