/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "platform/oz_platform.h"
#include "oz_dispatch.h"
#include "OZObject.h"

struct Timer {
	struct OZObject base;
	int _interval;
};

void Timer_start(struct Timer *self);
void Timer_stop(struct Timer *self);
void Timer_dealloc(struct Timer *self);

