# SPDX-License-Identifier: Apache-2.0
#
# emit.py - Pass 3: OZModule -> .h/.c files

from __future__ import annotations

import os
from dataclasses import dataclass, field
from io import StringIO

from .model import (DispatchKind, OZClass, OZFunction, OZMethod, OZModule,
                     OZParam, OZType)


@dataclass
class _EmitCtx:
    cls: OZClass
    module: OZModule
    root_class: str
    method: OZMethod | None = None
    scope_vars: list[dict[str, OZType]] = field(default_factory=list)
    consumed_vars: set[str] = field(default_factory=set)
    loop_scope_depth: list[int] = field(default_factory=list)


def emit(module: OZModule, outdir: str, pool_sizes: dict[str, int] | None = None,
         root_class: str = "OZObject") -> list[str]:
    """Generate C files from OZModule. Returns list of generated file paths."""
    os.makedirs(outdir, exist_ok=True)
    files = []

    files.append(_emit_dispatch_header(module, outdir))
    files.append(_emit_dispatch_source(module, outdir))
    files.extend(_emit_mem_slabs(module, outdir, pool_sizes or {}, root_class))

    for cls in module.classes.values():
        ctx = _EmitCtx(cls=cls, module=module, root_class=root_class)
        files.append(_emit_class_header(ctx, outdir))
        files.append(_emit_class_source(ctx, outdir))

    if module.functions:
        files.append(_emit_functions(module, outdir, root_class))

    return files


# ---------------------------------------------------------------------------
# oz_dispatch.h
# ---------------------------------------------------------------------------

def _emit_dispatch_header(module: OZModule, outdir: str) -> str:
    out = StringIO()
    out.write("/* Auto-generated by oz_transpile -- do not edit */\n")
    out.write("#pragma once\n\n")
    out.write("#include <stdint.h>\n")
    out.write("#include <stdbool.h>\n\n")
    out.write("#ifndef BOOL\n")
    out.write("#define BOOL _Bool\n")
    out.write("#endif\n\n")

    # Forward declare all class structs
    for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
        out.write(f"struct {cls.name};\n")
    out.write("\n")

    # Class ID enum
    out.write("enum oz_class_id {\n")
    for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
        out.write(f"\tOZ_CLASS_{cls.name} = {cls.class_id},\n")
    out.write(f"\tOZ_CLASS_COUNT = {len(module.classes)}\n")
    out.write("};\n\n")

    # Protocol dispatch macros
    _emit_protocol_macros(module, out)

    path = os.path.join(outdir, "oz_dispatch.h")
    _write_file(path, out.getvalue())
    return path


def _emit_protocol_macros(module: OZModule, out: StringIO) -> None:
    """Generate OZ_SEND macros for protocol-dispatched selectors."""
    # Collect all protocol-dispatched selectors with their signatures
    proto_sels: dict[str, OZMethod] = {}
    for cls in module.classes.values():
        for m in cls.methods:
            if m.dispatch == DispatchKind.PROTOCOL and m.selector not in proto_sels:
                proto_sels[m.selector] = m

    if not proto_sels:
        return

    out.write("/* Protocol dispatch function pointer types */\n")
    for sel, m in sorted(proto_sels.items()):
        c_sel = _selector_to_c(sel)
        ret = m.return_type.c_type
        param_types = ", ".join(
            ["struct OZObject *"] + [p.oz_type.c_type for p in m.params]
        )
        out.write(f"typedef {ret} (*OZ_fn_{c_sel})({param_types});\n")

    out.write("\n/* Protocol dispatch tables (indexed by oz_class_id) */\n")
    for sel, m in sorted(proto_sels.items()):
        c_sel = _selector_to_c(sel)
        out.write(f"extern OZ_fn_{c_sel} OZ_vtable_{c_sel}[OZ_CLASS_COUNT];\n")

    out.write("\n/* OZ_SEND macros (statement-expr to avoid double evaluation) */\n")
    for sel, m in sorted(proto_sels.items()):
        c_sel = _selector_to_c(sel)
        extra_params = [p.name for p in m.params]
        extra_args = ", ".join([f"({p.name})" for p in m.params])
        macro_params = ", ".join(["obj"] + extra_params)
        call = f"OZ_vtable_{c_sel}[_oz_obj->oz_class_id]"
        if extra_args:
            call += f"(_oz_obj, {extra_args})"
        else:
            call += "(_oz_obj)"
        out.write(
            f"#define OZ_SEND_{c_sel}({macro_params}) "
            f"__extension__({{ struct OZObject *_oz_obj = "
            f"(struct OZObject *)(obj); {call}; }})\n"
        )

    out.write("\n/* OZ_PROTOCOL_SEND (cast-free, same as OZ_SEND) */\n")
    for sel, m in sorted(proto_sels.items()):
        c_sel = _selector_to_c(sel)
        macro_params = ", ".join(["obj"] + [p.name for p in m.params])
        out.write(f"#define OZ_PROTOCOL_SEND_{c_sel}({macro_params}) "
                  f"OZ_SEND_{c_sel}({macro_params})\n")

    out.write("\n")


def _emit_dispatch_source(module: OZModule, outdir: str) -> str:
    """Generate oz_dispatch.c with vtable definitions and registration."""
    out = StringIO()
    out.write("/* Auto-generated by oz_transpile -- do not edit */\n")
    out.write("#include \"oz_dispatch.h\"\n")

    # Include all class headers (needed for function pointer casts)
    for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
        out.write(f"#include \"{cls.name}.h\"\n")
    out.write("\n")

    # Collect all protocol-dispatched selectors
    emitted: set[str] = set()
    for cls in module.classes.values():
        for m in cls.methods:
            if m.dispatch == DispatchKind.PROTOCOL and m.selector not in emitted:
                c_sel = _selector_to_c(m.selector)
                out.write(f"OZ_fn_{c_sel} OZ_vtable_{c_sel}[OZ_CLASS_COUNT];\n")
                emitted.add(m.selector)

    # Generate oz_register_vtables()
    _emit_vtable_registration(module, out)

    path = os.path.join(outdir, "oz_dispatch.c")
    _write_file(path, out.getvalue())
    return path


def _emit_vtable_registration(module: OZModule, out: StringIO) -> None:
    """Generate oz_register_vtables() that populates all protocol vtable entries."""
    # Collect protocol entries: (selector, class, method) triples
    entries: list[tuple[str, OZClass, OZMethod]] = []
    for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
        for m in cls.methods:
            if m.dispatch == DispatchKind.PROTOCOL:
                entries.append((_selector_to_c(m.selector), cls, m))

    if not entries:
        return

    out.write("\n__attribute__((constructor))\n")
    out.write("static void oz_register_vtables(void)\n")
    out.write("{\n")

    # For each protocol selector, walk the class hierarchy to fill vtable slots.
    # Each class gets the most specific implementation.
    proto_sels: dict[str, OZMethod] = {}
    for cls in module.classes.values():
        for m in cls.methods:
            if m.dispatch == DispatchKind.PROTOCOL and m.selector not in proto_sels:
                proto_sels[m.selector] = m

    for sel_name in sorted(proto_sels.keys()):
        c_sel = _selector_to_c(sel_name)
        # For each class, find the implementing class (walk up hierarchy)
        for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
            impl_cls = _find_implementing_class(cls, sel_name, module)
            if impl_cls:
                out.write(f"\tOZ_vtable_{c_sel}[OZ_CLASS_{cls.name}] = "
                          f"(OZ_fn_{c_sel}){impl_cls.name}_{c_sel};\n")

    out.write("}\n")


def _find_implementing_class(cls: OZClass, selector: str,
                             module: OZModule) -> OZClass | None:
    """Walk up the class hierarchy to find which class implements the selector."""
    cur: OZClass | None = cls
    while cur:
        for m in cur.methods:
            if m.selector == selector:
                return cur
        if cur.superclass and cur.superclass in module.classes:
            cur = module.classes[cur.superclass]
        else:
            break
    return None


# ---------------------------------------------------------------------------
# oz_mem_slabs.h
# ---------------------------------------------------------------------------

def _emit_mem_slabs(module: OZModule, outdir: str,
                    pool_sizes: dict[str, int], root_class: str) -> list[str]:
    """Generate oz_mem_slabs.h (declarations + inline) and oz_mem_slabs.c (definitions)."""
    files = []

    # --- Header ---
    out = StringIO()
    out.write("/* Auto-generated by oz_transpile -- do not edit */\n")
    out.write("#pragma once\n\n")
    out.write("#include <zephyr/kernel.h>\n")
    out.write("#include <string.h>\n\n")

    # Include all class headers so struct types are complete
    for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
        out.write(f"#include \"{cls.name}.h\"\n")
    out.write("\n")

    # Extern declarations for slabs
    for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
        out.write(f"extern struct k_mem_slab oz_slab_{cls.name};\n")
    out.write("\n")

    # Inline alloc/free
    for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
        base_chain = _base_chain(cls.name, module)
        out.write(f"static inline struct {cls.name} *{cls.name}_alloc(void)\n")
        out.write("{\n")
        out.write(f"\tstruct {cls.name} *obj;\n")
        out.write(f"\tif (k_mem_slab_alloc(&oz_slab_{cls.name}, "
                  f"(void **)&obj, K_NO_WAIT) != 0) {{\n")
        out.write(f"\t\treturn (struct {cls.name} *)0;\n")
        out.write("\t}\n")
        out.write(f"\tmemset(obj, 0, sizeof(struct {cls.name}));\n")
        out.write(f"\t{base_chain}oz_class_id = OZ_CLASS_{cls.name};\n")
        out.write(f"\t{base_chain}_refcount = 1;\n")
        out.write("\treturn obj;\n")
        out.write("}\n\n")

        out.write(f"static inline void {cls.name}_free(struct {cls.name} *obj)\n")
        out.write("{\n")
        out.write(f"\tk_mem_slab_free(&oz_slab_{cls.name}, (void *)obj);\n")
        out.write("}\n\n")

    # Dispatch free by oz_class_id (root dealloc calls this)
    out.write(f"static inline void {root_class}_dispatch_free(struct {root_class} *obj)\n")
    out.write("{\n")
    out.write("\tswitch (obj->oz_class_id) {\n")
    for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
        out.write(f"\tcase OZ_CLASS_{cls.name}: "
                  f"{cls.name}_free((struct {cls.name} *)obj); break;\n")
    out.write("\t}\n")
    out.write("}\n\n")

    h_path = os.path.join(outdir, "oz_mem_slabs.h")
    _write_file(h_path, out.getvalue())
    files.append(h_path)

    # --- Source ---
    out = StringIO()
    out.write("/* Auto-generated by oz_transpile -- do not edit */\n")
    out.write("#include \"oz_mem_slabs.h\"\n\n")

    auto_counts = _count_alloc_calls(module)
    for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
        count = pool_sizes.get(cls.name, max(auto_counts.get(cls.name, 0), 1))
        out.write(f"K_MEM_SLAB_DEFINE(oz_slab_{cls.name}, "
                  f"sizeof(struct {cls.name}), {count}, 4);\n")

    c_path = os.path.join(outdir, "oz_mem_slabs.c")
    _write_file(c_path, out.getvalue())
    files.append(c_path)

    return files


# ---------------------------------------------------------------------------
# Per-class .h
# ---------------------------------------------------------------------------

def _emit_class_header(ctx: _EmitCtx, outdir: str) -> str:
    cls = ctx.cls
    module = ctx.module
    out = StringIO()
    out.write("/* Auto-generated by oz_transpile -- do not edit */\n")
    out.write("#pragma once\n\n")
    out.write("#include \"oz_dispatch.h\"\n")
    if cls.superclass and cls.superclass in module.classes:
        out.write(f"#include \"{cls.superclass}.h\"\n")
    out.write("\n")

    # Struct
    _root_builtins = {"_refcount", "oz_class_id"}
    is_root = not cls.superclass or cls.superclass not in module.classes
    out.write(f"struct {cls.name} {{\n")
    if not is_root:
        out.write(f"\tstruct {cls.superclass} base;\n")
    else:
        out.write("\tuint8_t oz_class_id;\n")
        out.write("\tuint32_t _refcount;\n")
    for ivar in cls.ivars:
        if is_root and ivar.name in _root_builtins:
            continue
        out.write(f"\t{ivar.oz_type.c_type} {ivar.name};\n")
    out.write("};\n\n")

    # Root class always gets retain/release/retainCount prototypes
    if is_root:
        out.write(f"struct {cls.name} *{cls.name}_retain(struct {cls.name} *self);\n")
        out.write(f"void {cls.name}_release(struct {cls.name} *self);\n")
        out.write(f"uint32_t {cls.name}_retainCount(struct {cls.name} *self);\n")

    # Method prototypes
    has_dealloc = False
    for m in cls.methods:
        if is_root and m.selector in ("retain", "release", "retainCount"):
            continue
        if m.selector == "dealloc":
            has_dealloc = True
        out.write(f"{_method_prototype(cls, m)};\n")

    # Add dealloc prototype if it will be auto-generated
    if not has_dealloc:
        obj_ivars = [iv for iv in cls.ivars if iv.oz_type.is_object]
        if obj_ivars or not is_root:
            out.write(f"void {cls.name}_dealloc(struct {cls.name} *self);\n")

    if cls.methods or is_root:
        out.write("\n")

    path = os.path.join(outdir, f"{cls.name}.h")
    _write_file(path, out.getvalue())
    return path


# ---------------------------------------------------------------------------
# Per-class .c
# ---------------------------------------------------------------------------

def _emit_class_source(ctx: _EmitCtx, outdir: str) -> str:
    cls = ctx.cls
    module = ctx.module
    root_class = ctx.root_class
    out = StringIO()
    out.write("/* Auto-generated by oz_transpile -- do not edit */\n")
    out.write(f"#include \"{cls.name}.h\"\n")
    out.write("#include \"oz_mem_slabs.h\"\n")
    if cls.name == root_class:
        out.write("#include <zephyr/sys/atomic.h>\n")
    out.write("\n")

    # Emit retain/release for root class
    if cls.name == root_class:
        _emit_root_retain_release(cls, module, out)

    has_user_dealloc = False
    for m in cls.methods:
        if m.selector in ("retain", "release", "retainCount") and cls.name == root_class:
            continue
        if m.selector == "dealloc":
            has_user_dealloc = True
            _emit_user_dealloc(ctx, m, out)
            continue
        ctx.method = m
        ctx.scope_vars = []
        ctx.consumed_vars = set()
        ctx.loop_scope_depth = []
        out.write(f"{_method_prototype(cls, m)}\n")
        if m.body_ast:
            _emit_compound_stmt(m.body_ast, out, ctx, indent=0,
                                param_retains=_object_params(m))
        else:
            out.write("{\n}\n")
        out.write("\n")

    # Auto-generate dealloc if not user-defined
    if not has_user_dealloc:
        _emit_auto_dealloc(ctx, out)

    path = os.path.join(outdir, f"{cls.name}.c")
    _write_file(path, out.getvalue())
    return path


# ---------------------------------------------------------------------------
# Root class retain/release
# ---------------------------------------------------------------------------

def _emit_root_retain_release(cls: OZClass, module: OZModule,
                              out: StringIO) -> None:
    out.write(f"struct {cls.name} *{cls.name}_retain(struct {cls.name} *self)\n")
    out.write("{\n")
    out.write("\tif (self) {\n")
    out.write(f"\t\tatomic_inc((atomic_t *)&self->_refcount);\n")
    out.write("\t}\n")
    out.write("\treturn self;\n")
    out.write("}\n\n")

    out.write(f"void {cls.name}_release(struct {cls.name} *self)\n")
    out.write("{\n")
    out.write("\tif (!self) {\n")
    out.write("\t\treturn;\n")
    out.write("\t}\n")
    out.write(f"\tatomic_val_t old = atomic_dec((atomic_t *)&self->_refcount);\n")
    out.write("\tif (old == 1) {\n")
    out.write(f"\t\tOZ_SEND_dealloc((struct {cls.name} *)self);\n")
    out.write("\t}\n")
    out.write("}\n\n")

    out.write(f"uint32_t {cls.name}_retainCount(struct {cls.name} *self)\n")
    out.write("{\n")
    out.write("\tif (!self) {\n")
    out.write("\t\treturn 0;\n")
    out.write("\t}\n")
    out.write(f"\treturn (uint32_t)atomic_get((atomic_t *)&self->_refcount);\n")
    out.write("}\n\n")


# ---------------------------------------------------------------------------
# Body AST -> C
# ---------------------------------------------------------------------------

def _emit_compound_stmt(node: dict, out: StringIO, ctx: _EmitCtx,
                        indent: int = 0, inline: bool = False,
                        param_retains: list[OZParam] | None = None) -> None:
    if inline:
        out.write("{\n")
    else:
        out.write("\t" * indent + "{\n")

    # Push scope frame
    ctx.scope_vars.append({})

    # Retain and track object params at method/function entry
    if param_retains:
        tabs_inner = "\t" * (indent + 1)
        for p in param_retains:
            out.write(f"{tabs_inner}{ctx.root_class}_retain("
                      f"(struct {ctx.root_class} *){p.name});\n")
            ctx.scope_vars[-1][p.name] = p.oz_type

    children = node.get("inner", [])
    for i, child in enumerate(children):
        _emit_stmt(child, out, ctx, indent + 1)

    # Release locals at scope exit (skip if last stmt is a return — it handles cleanup)
    last_kind = children[-1].get("kind", "") if children else ""
    if last_kind != "ReturnStmt":
        _emit_scope_releases(out, ctx, indent + 1)

    # Pop scope frame
    ctx.scope_vars.pop()

    out.write("\t" * indent + "}\n")


def _emit_stmt(node: dict, out: StringIO, ctx: _EmitCtx,
               indent: int) -> None:
    tabs = "\t" * indent
    kind = node.get("kind", "")

    if kind == "ReturnStmt":
        _emit_return_stmt(node, out, ctx, indent)

    elif kind == "DeclStmt":
        for decl in node.get("inner", []):
            if decl.get("kind") == "VarDecl":
                _emit_var_decl(decl, out, ctx, indent)

    elif kind == "IfStmt":
        _emit_if_stmt(node, out, ctx, indent)

    elif kind == "ForStmt":
        _emit_for_stmt(node, out, ctx, indent)

    elif kind == "WhileStmt":
        inner = node.get("inner", [])
        if len(inner) >= 2:
            out.write(f"{tabs}while (")
            _emit_expr(inner[0], out, ctx)
            out.write(") ")
            ctx.loop_scope_depth.append(len(ctx.scope_vars))
            if inner[1].get("kind") == "CompoundStmt":
                _emit_compound_stmt(inner[1], out, ctx, indent, inline=True)
            else:
                out.write("{\n")
                _emit_stmt(inner[1], out, ctx, indent + 1)
                out.write(f"{tabs}}}\n")
            ctx.loop_scope_depth.pop()

    elif kind == "DoStmt":
        inner = node.get("inner", [])
        if len(inner) >= 2:
            out.write(f"{tabs}do ")
            ctx.loop_scope_depth.append(len(ctx.scope_vars))
            if inner[0].get("kind") == "CompoundStmt":
                _emit_compound_stmt(inner[0], out, ctx, indent, inline=True)
            else:
                out.write("{\n")
                _emit_stmt(inner[0], out, ctx, indent + 1)
                out.write(f"{tabs}}}\n")
            ctx.loop_scope_depth.pop()
            out.write(f"{tabs}while (")
            _emit_expr(inner[1], out, ctx)
            out.write(");\n")

    elif kind == "CompoundStmt":
        _emit_compound_stmt(node, out, ctx, indent)

    elif kind == "ObjCAutoreleasePoolStmt":
        inner = node.get("inner", [])
        if inner and inner[0].get("kind") == "CompoundStmt":
            _emit_compound_stmt(inner[0], out, ctx, indent)

    elif kind == "NullStmt":
        out.write(f"{tabs};\n")

    elif kind == "BreakStmt":
        _emit_break_continue_releases(out, ctx, indent)
        out.write(f"{tabs}break;\n")

    elif kind == "ContinueStmt":
        _emit_break_continue_releases(out, ctx, indent)
        out.write(f"{tabs}continue;\n")

    elif kind == "CompoundAssignOperator":
        out.write(tabs)
        _emit_expr(node, out, ctx)
        out.write(";\n")

    elif kind == "BinaryOperator" and node.get("opcode") == "=":
        # Check for strong ivar assignment
        inner = node.get("inner", [])
        if len(inner) == 2 and _is_object_ivar_assign(inner[0], ctx):
            _emit_strong_ivar_assign(node, out, ctx, indent)
        else:
            out.write(tabs)
            _emit_expr(node, out, ctx)
            out.write(";\n")

    else:
        # Expression statement
        out.write(tabs)
        _emit_expr(node, out, ctx)
        out.write(";\n")


def _emit_var_decl(node: dict, out: StringIO, ctx: _EmitCtx,
                   indent: int) -> None:
    tabs = "\t" * indent
    qt = node.get("type", {}).get("qualType", "int")
    oz_type = OZType(qt)
    name = node.get("name", "_anon")
    c_type = oz_type.c_type

    # Track object locals for scope-exit release (never track self)
    if oz_type.is_object and name != "self" and ctx.scope_vars:
        ctx.scope_vars[-1][name] = oz_type

    inner = node.get("inner", [])
    init_expr = None
    for child in inner:
        if child.get("kind") not in ("FullComment",):
            init_expr = child
            break

    if init_expr:
        out.write(f"{tabs}{c_type} {name} = ")
        _emit_expr(init_expr, out, ctx)
        out.write(";\n")
    else:
        out.write(f"{tabs}{c_type} {name};\n")


def _emit_if_stmt(node: dict, out: StringIO, ctx: _EmitCtx,
                  indent: int) -> None:
    tabs = "\t" * indent
    inner = node.get("inner", [])
    if not inner:
        return

    has_else = node.get("hasElse", False)

    # Clang AST: inner[0]=cond, inner[1]=then, [inner[2]=else]
    cond = inner[0]
    then_body = inner[1] if len(inner) > 1 else None
    else_body = inner[2] if has_else and len(inner) > 2 else None

    out.write(f"{tabs}if (")
    _emit_expr(cond, out, ctx)
    out.write(") ")
    if then_body:
        if then_body.get("kind") == "CompoundStmt":
            _emit_compound_stmt(then_body, out, ctx, indent, inline=True)
        else:
            out.write("{\n")
            _emit_stmt(then_body, out, ctx, indent + 1)
            out.write(f"{tabs}}}\n")

    if else_body:
        if else_body.get("kind") == "IfStmt":
            out.write(f"{tabs}else ")
            _emit_if_stmt(else_body, out, ctx, indent)
        elif else_body.get("kind") == "CompoundStmt":
            out.write(f"{tabs}else ")
            _emit_compound_stmt(else_body, out, ctx, indent, inline=True)
        else:
            out.write(f"{tabs}else {{\n")
            _emit_stmt(else_body, out, ctx, indent + 1)
            out.write(f"{tabs}}}\n")


def _emit_for_stmt(node: dict, out: StringIO, ctx: _EmitCtx,
                   indent: int) -> None:
    tabs = "\t" * indent
    inner = node.get("inner", [])
    if len(inner) < 2:
        return

    out.write(f"{tabs}for (")
    # init
    if len(inner) > 0 and inner[0].get("kind") not in ("NullStmt", "<<<NULL>>>"):
        if inner[0].get("kind") == "DeclStmt":
            decls = inner[0].get("inner", [])
            if decls and decls[0].get("kind") == "VarDecl":
                vd = decls[0]
                qt = vd.get("type", {}).get("qualType", "int")
                vname = vd.get("name", "i")
                c_type = OZType(qt).c_type
                vinit = [c for c in vd.get("inner", []) if c.get("kind") != "FullComment"]
                out.write(f"{c_type} {vname}")
                if vinit:
                    out.write(" = ")
                    _emit_expr(vinit[0], out, ctx)
        else:
            _emit_expr(inner[0], out, ctx)
    out.write("; ")

    # cond (index 2 in Clang AST; index 1 might be condVar)
    cond_idx = 2 if len(inner) > 4 else 1
    if cond_idx < len(inner) and inner[cond_idx].get("kind") not in ("NullStmt", "<<<NULL>>>"):
        _emit_expr(inner[cond_idx], out, ctx)
    out.write("; ")

    # inc
    inc_idx = 3 if len(inner) > 4 else 2
    if inc_idx < len(inner) and inner[inc_idx].get("kind") not in ("NullStmt", "<<<NULL>>>"):
        _emit_expr(inner[inc_idx], out, ctx)
    out.write(") ")

    # body
    body_idx = 4 if len(inner) > 4 else len(inner) - 1
    body = inner[body_idx] if body_idx < len(inner) else None
    ctx.loop_scope_depth.append(len(ctx.scope_vars))
    if body and body.get("kind") == "CompoundStmt":
        _emit_compound_stmt(body, out, ctx, indent, inline=True)
    elif body:
        out.write("{\n")
        _emit_stmt(body, out, ctx, indent + 1)
        out.write(f"{tabs}}}\n")
    else:
        out.write("{}\n")
    ctx.loop_scope_depth.pop()


def _emit_expr(node: dict, out: StringIO, ctx: _EmitCtx) -> None:
    kind = node.get("kind", "")

    if kind == "ImplicitCastExpr":
        inner = node.get("inner", [])
        if inner:
            _emit_expr(inner[0], out, ctx)
        return

    if kind == "CStyleCastExpr":
        if node.get("castKind") == "NullToPointer":
            out.write("((void *)0)")
            return
        qt = node.get("type", {}).get("qualType", "")
        out.write(f"({OZType(qt).c_type})")
        inner = node.get("inner", [])
        if inner:
            _emit_expr(inner[0], out, ctx)
        return

    if kind == "ParenExpr":
        out.write("(")
        inner = node.get("inner", [])
        if inner:
            _emit_expr(inner[0], out, ctx)
        out.write(")")
        return

    if kind == "ObjCMessageExpr":
        _emit_msg_expr(node, out, ctx)
        return

    if kind == "ObjCIvarRefExpr":
        ivar_name = node.get("decl", {}).get("name", "")
        out.write(f"self->{ivar_name}")
        return

    if kind == "DeclRefExpr":
        name = node.get("referencedDecl", {}).get("name", "")
        out.write(name)
        return

    if kind == "MemberExpr":
        inner = node.get("inner", [])
        member = node.get("name", "")
        is_arrow = node.get("isArrow", False)
        if inner:
            _emit_expr(inner[0], out, ctx)
        out.write(f"->{member}" if is_arrow else f".{member}")
        return

    if kind == "BinaryOperator":
        inner = node.get("inner", [])
        op = node.get("opcode", "")
        if len(inner) == 2:
            _emit_expr(inner[0], out, ctx)
            out.write(f" {op} ")
            _emit_expr(inner[1], out, ctx)
        return

    if kind == "CompoundAssignOperator":
        inner = node.get("inner", [])
        op = node.get("opcode", "")
        if len(inner) == 2:
            _emit_expr(inner[0], out, ctx)
            out.write(f" {op} ")
            _emit_expr(inner[1], out, ctx)
        return

    if kind == "UnaryOperator":
        inner = node.get("inner", [])
        op = node.get("opcode", "")
        is_postfix = node.get("isPostfix", False)
        if inner:
            if is_postfix:
                _emit_expr(inner[0], out, ctx)
                out.write(op)
            else:
                out.write(op)
                _emit_expr(inner[0], out, ctx)
        return

    if kind == "ConditionalOperator":
        inner = node.get("inner", [])
        if len(inner) == 3:
            _emit_expr(inner[0], out, ctx)
            out.write(" ? ")
            _emit_expr(inner[1], out, ctx)
            out.write(" : ")
            _emit_expr(inner[2], out, ctx)
        return

    if kind == "IntegerLiteral":
        out.write(node.get("value", "0"))
        return

    if kind == "FloatingLiteral":
        out.write(node.get("value", "0.0"))
        return

    if kind == "CharacterLiteral":
        val = node.get("value", 0)
        if 32 <= val < 127 and val != ord("'") and val != ord("\\"):
            out.write(f"'{chr(val)}'")
        else:
            out.write(str(val))
        return

    if kind == "StringLiteral":
        out.write(node.get("value", '""'))
        return

    if kind == "ObjCStringLiteral":
        inner = node.get("inner", [])
        if inner:
            out.write(inner[0].get("value", '""'))
        return

    if kind == "ObjCBoolLiteralExpr":
        val = node.get("value", False)
        if isinstance(val, str):
            out.write("0" if "no" in val.lower() else "1")
        else:
            out.write("1" if val else "0")
        return

    if kind == "GNUNullExpr" or kind == "CXXNullPtrLiteralExpr":
        out.write("((void *)0)")
        return

    if kind == "PseudoObjectExpr":
        inner = node.get("inner", [])
        if inner:
            _emit_expr(inner[0], out, ctx)
        return

    if kind == "OpaqueValueExpr":
        inner = node.get("inner", [])
        if inner:
            _emit_expr(inner[0], out, ctx)
        return

    if kind == "CallExpr":
        inner = node.get("inner", [])
        if inner:
            _emit_expr(inner[0], out, ctx)
            out.write("(")
            args = inner[1:]
            for i, arg in enumerate(args):
                if i > 0:
                    out.write(", ")
                _emit_expr(arg, out, ctx)
            out.write(")")
        return

    if kind == "ArraySubscriptExpr":
        inner = node.get("inner", [])
        if len(inner) == 2:
            _emit_expr(inner[0], out, ctx)
            out.write("[")
            _emit_expr(inner[1], out, ctx)
            out.write("]")
        return

    # Fallback: try inner children or emit placeholder
    inner = node.get("inner", [])
    if inner:
        _emit_expr(inner[0], out, ctx)
    else:
        out.write(f"/* TODO: {kind} */")


def _emit_msg_expr(node: dict, out: StringIO, ctx: _EmitCtx) -> None:
    cls = ctx.cls
    module = ctx.module
    root_class = ctx.root_class
    selector = node.get("selector", "")
    c_sel = _selector_to_c(selector)
    receiver_kind = node.get("receiverKind", "")
    inner = node.get("inner", [])

    # [super sel] -> ParentClass_sel((struct ParentClass *)self)
    if receiver_kind.startswith("super"):
        parent = cls.superclass or root_class
        ret_type = node.get("type", {}).get("qualType", "void")
        needs_cast = OZType(ret_type).is_object
        if needs_cast:
            out.write(f"(struct {cls.name} *)")
        out.write(f"{parent}_{c_sel}(")
        out.write(f"(struct {parent} *)self")
        for arg in inner:
            out.write(", ")
            _emit_expr(arg, out, ctx)
        out.write(")")
        return

    # [ClassName alloc] -> ClassName_alloc()
    if receiver_kind == "class":
        class_type = node.get("classType", {}).get("qualType", "")
        out.write(f"{class_type}_{c_sel}(")
        for i, arg in enumerate(inner):
            if i > 0:
                out.write(", ")
            _emit_expr(arg, out, ctx)
        out.write(")")
        return

    # [obj sel] -> check dispatch kind
    args_exprs = _collect_msg_args(inner)
    receiver = inner[0] if inner else None

    dispatch = _find_dispatch_kind(selector, module)
    if dispatch == DispatchKind.PROTOCOL:
        # Protocol vtable returns root class pointer; cast if the method
        # returns an object type and the receiver is a subclass
        ret_qt = node.get("type", {}).get("qualType", "void")
        ret_oz = OZType(ret_qt)
        recv_class = _infer_receiver_class(receiver, cls, module) if receiver else cls.name
        needs_cast = ret_oz.is_object and recv_class != root_class
        if needs_cast:
            out.write(f"(struct {recv_class} *)")
        out.write(f"OZ_SEND_{c_sel}(")
        if receiver:
            _emit_expr(receiver, out, ctx)
        for arg in args_exprs:
            out.write(", ")
            _emit_expr(arg, out, ctx)
        out.write(")")
    else:
        recv_class = _infer_receiver_class(receiver, cls, module) if receiver else cls.name
        out.write(f"{recv_class}_{c_sel}(")
        if receiver:
            _emit_expr(receiver, out, ctx)
        for arg in args_exprs:
            out.write(", ")
            _emit_expr(arg, out, ctx)
        out.write(")")


def _collect_msg_args(inner: list[dict]) -> list[dict]:
    """Extract argument expressions from ObjCMessageExpr inner nodes.

    inner[0] is the receiver, the rest are arguments.
    """
    if len(inner) <= 1:
        return []
    return inner[1:]


def _find_dispatch_kind(selector: str, module: OZModule) -> DispatchKind:
    for cls in module.classes.values():
        for m in cls.methods:
            if m.selector == selector:
                return m.dispatch
    return DispatchKind.STATIC


def _infer_receiver_class(node: dict, cls: OZClass, module: OZModule | None = None) -> str:
    """Best-effort receiver class from AST type info."""
    qt = node.get("type", {}).get("qualType", "")
    oz = OZType(qt)
    if oz.is_object:
        name = oz._strip_qualifiers().rstrip(" *")
        if name and name not in ("id", "instancetype"):
            return name

    # If the receiver is a message expr, try to infer from classType or receiver chain
    unwrapped = node
    while unwrapped.get("kind") in ("ImplicitCastExpr", "ParenExpr"):
        inner = unwrapped.get("inner", [])
        if inner:
            unwrapped = inner[0]
        else:
            break
    if unwrapped.get("kind") == "ObjCMessageExpr":
        ct = unwrapped.get("classType", {}).get("qualType", "")
        if ct and ct in (module.classes if module else {}):
            return ct

    return cls.name


# ---------------------------------------------------------------------------
# Top-level functions
# ---------------------------------------------------------------------------

def _emit_functions(module: OZModule, outdir: str, root_class: str) -> str:
    """Generate oz_functions.c with top-level C functions from the ObjC source."""
    out = StringIO()
    out.write("/* Auto-generated by oz_transpile -- do not edit */\n")
    out.write("#include <zephyr/kernel.h>\n")
    out.write("#include <zephyr/sys/printk.h>\n")
    out.write("#include \"oz_dispatch.h\"\n")
    out.write("#include \"oz_mem_slabs.h\"\n")
    for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
        out.write(f"#include \"{cls.name}.h\"\n")
    out.write("\n")

    # Use a dummy OZClass for body emission context (free functions use OZObject)
    dummy_cls = module.classes.get(root_class, OZClass(name=root_class))
    ctx = _EmitCtx(cls=dummy_cls, module=module, root_class=root_class)

    for func in module.functions:
        ret = func.return_type.c_type
        params_str = ", ".join(
            f"{p.oz_type.c_type} {p.name}" for p in func.params
        )
        if not params_str:
            params_str = "void"
        out.write(f"{ret} {func.name}({params_str})\n")
        ctx.method = None
        ctx.scope_vars = []
        ctx.consumed_vars = set()
        ctx.loop_scope_depth = []
        if func.body_ast:
            _emit_compound_stmt(func.body_ast, out, ctx, indent=0,
                                param_retains=_object_params(func))
        else:
            out.write("{\n}\n")
        out.write("\n")

    path = os.path.join(outdir, "oz_functions.c")
    _write_file(path, out.getvalue())
    return path


# ---------------------------------------------------------------------------
# ARC: scope tracking, return cleanup, dealloc, strong ivar assign
# ---------------------------------------------------------------------------

def _object_params(m: OZMethod | OZFunction) -> list[OZParam]:
    """Return object-typed params (excluding self, which is implicit)."""
    return [p for p in m.params if p.oz_type.is_object]


def _emit_break_continue_releases(out: StringIO, ctx: _EmitCtx,
                                   indent: int) -> None:
    """Emit release calls for all object vars from current scope down to loop boundary."""
    if not ctx.loop_scope_depth:
        return
    tabs = "\t" * indent
    loop_depth = ctx.loop_scope_depth[-1]
    for i in range(len(ctx.scope_vars) - 1, loop_depth - 1, -1):
        if i < 0 or i >= len(ctx.scope_vars):
            continue
        frame = ctx.scope_vars[i]
        for name in frame:
            if name not in ctx.consumed_vars:
                out.write(f"{tabs}{ctx.root_class}_release("
                          f"(struct {ctx.root_class} *){name});\n")


def _emit_scope_releases(out: StringIO, ctx: _EmitCtx, indent: int) -> None:
    """Emit release calls for object vars in the current (top) scope frame."""
    if not ctx.scope_vars:
        return
    tabs = "\t" * indent
    frame = ctx.scope_vars[-1]
    for name in frame:
        if name not in ctx.consumed_vars:
            out.write(f"{tabs}{ctx.root_class}_release("
                      f"(struct {ctx.root_class} *){name});\n")


def _emit_return_stmt(node: dict, out: StringIO, ctx: _EmitCtx,
                      indent: int) -> None:
    """Emit return statement with ARC cleanup of all in-scope object vars."""
    tabs = "\t" * indent
    inner = node.get("inner", [])

    # Find the name of the returned variable (if any) to skip its release
    returned_var = _find_returned_var(inner[0]) if inner else None

    # Release all in-scope object vars except returned var and self
    all_vars = _flatten_scope_vars(ctx)
    for name in all_vars:
        if name == returned_var or name in ctx.consumed_vars:
            continue
        out.write(f"{tabs}{ctx.root_class}_release("
                  f"(struct {ctx.root_class} *){name});\n")

    if inner:
        out.write(f"{tabs}return ")
        _emit_expr(inner[0], out, ctx)
        out.write(";\n")
    else:
        out.write(f"{tabs}return;\n")


def _find_returned_var(node: dict) -> str | None:
    """Walk through casts to find a DeclRefExpr name in a return expression."""
    if not node:
        return None
    kind = node.get("kind", "")
    if kind == "DeclRefExpr":
        return node.get("referencedDecl", {}).get("name")
    if kind in ("ImplicitCastExpr", "CStyleCastExpr", "ParenExpr"):
        inner = node.get("inner", [])
        if inner:
            return _find_returned_var(inner[0])
    return None


def _flatten_scope_vars(ctx: _EmitCtx) -> list[str]:
    """Collect all object var names from all scope frames."""
    result = []
    for frame in ctx.scope_vars:
        for name in frame:
            result.append(name)
    return result


def _is_param_name(name: str, ctx: _EmitCtx) -> bool:
    """Check if a variable name is a method/function parameter."""
    if ctx.method:
        return any(p.name == name for p in ctx.method.params)
    return False


def _is_object_ivar_assign(lhs_node: dict, ctx: _EmitCtx) -> bool:
    """Check if LHS of an assignment is an object ivar."""
    unwrapped = lhs_node
    while unwrapped.get("kind") in ("ImplicitCastExpr",):
        inner = unwrapped.get("inner", [])
        if inner:
            unwrapped = inner[0]
        else:
            break
    if unwrapped.get("kind") != "ObjCIvarRefExpr":
        return False
    ivar_name = unwrapped.get("decl", {}).get("name", "")
    for ivar in ctx.cls.ivars:
        if ivar.name == ivar_name and ivar.oz_type.is_object:
            return True
    return False


def _emit_strong_ivar_assign(node: dict, out: StringIO, ctx: _EmitCtx,
                              indent: int) -> None:
    """Emit retain(new); release(old); ivar = new; for object ivar assignment."""
    tabs = "\t" * indent
    inner = node.get("inner", [])
    lhs = inner[0]
    rhs = inner[1]
    root = ctx.root_class

    # Get ivar name
    unwrapped = lhs
    while unwrapped.get("kind") in ("ImplicitCastExpr",):
        unwrapped = unwrapped.get("inner", [unwrapped])[0]
    ivar_name = unwrapped.get("decl", {}).get("name", "")

    # Emit: retain new, release old, assign
    rhs_buf = StringIO()
    _emit_expr(rhs, rhs_buf, ctx)
    rhs_str = rhs_buf.getvalue()

    out.write(f"{tabs}{root}_retain((struct {root} *){rhs_str});\n")
    out.write(f"{tabs}{root}_release((struct {root} *)self->{ivar_name});\n")
    out.write(f"{tabs}self->{ivar_name} = {rhs_str};\n")

    # Track consumed local: if RHS is a simple DeclRefExpr local, mark consumed.
    # Skip params — they have their own entry-retain balanced by scope-exit release.
    rhs_var = _find_returned_var(rhs)
    if rhs_var and rhs_var != "self":
        is_param = _is_param_name(rhs_var, ctx)
        if not is_param:
            for frame in ctx.scope_vars:
                if rhs_var in frame:
                    ctx.consumed_vars.add(rhs_var)
                    break


def _emit_user_dealloc(ctx: _EmitCtx, m: OZMethod, out: StringIO) -> None:
    """Emit user-defined dealloc with prepended ivar releases and appended parent dealloc."""
    cls = ctx.cls
    module = ctx.module
    root_class = ctx.root_class
    is_root = not cls.superclass or cls.superclass not in module.classes
    obj_ivars = [iv for iv in cls.ivars if iv.oz_type.is_object]

    out.write(f"{_method_prototype(cls, m)}\n")
    out.write("{\n")

    # Prepend: release object ivars
    for iv in obj_ivars:
        out.write(f"\t{root_class}_release((struct {root_class} *)self->{iv.name});\n")

    # Emit user body statements, filtering out [super dealloc]
    if m.body_ast:
        ctx.method = m
        ctx.scope_vars = []
        ctx.consumed_vars = set()
        for child in m.body_ast.get("inner", []):
            if _is_super_dealloc(child):
                continue
            _emit_stmt(child, out, ctx, indent=1)

    # Append: parent dealloc or dispatch_free (root)
    if not is_root:
        parent = cls.superclass
        out.write(f"\t{parent}_dealloc((struct {parent} *)self);\n")
    else:
        out.write(f"\t{root_class}_dispatch_free((struct {root_class} *)self);\n")

    out.write("}\n\n")


def _is_super_dealloc(node: dict) -> bool:
    """Check if a statement is [super dealloc]."""
    if node.get("kind") == "ObjCMessageExpr":
        if (node.get("selector") == "dealloc" and
                node.get("receiverKind", "").startswith("super")):
            return True
    return False


def _emit_auto_dealloc(ctx: _EmitCtx, out: StringIO) -> None:
    """Auto-generate dealloc method if class has object ivars or needs parent chain."""
    cls = ctx.cls
    module = ctx.module
    root_class = ctx.root_class
    is_root = not cls.superclass or cls.superclass not in module.classes

    # Collect object ivars
    obj_ivars = [iv for iv in cls.ivars if iv.oz_type.is_object]

    # Only generate if there are object ivars or a parent dealloc to call
    if not obj_ivars and is_root:
        return

    out.write(f"void {cls.name}_dealloc(struct {cls.name} *self)\n")
    out.write("{\n")

    for iv in obj_ivars:
        out.write(f"\t{root_class}_release((struct {root_class} *)self->{iv.name});\n")

    if not is_root:
        parent = cls.superclass
        out.write(f"\t{parent}_dealloc((struct {parent} *)self);\n")
    else:
        out.write(f"\t{root_class}_dispatch_free((struct {root_class} *)self);\n")

    out.write("}\n\n")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _count_alloc_calls(module: OZModule) -> dict[str, int]:
    """Count [ClassName alloc] calls across all method/function body ASTs."""
    counts: dict[str, int] = {}

    def walk(node: dict) -> None:
        if (node.get("kind") == "ObjCMessageExpr" and
                node.get("selector") == "alloc" and
                node.get("receiverKind") == "class"):
            class_name = node.get("classType", {}).get("qualType", "")
            if class_name:
                counts[class_name] = counts.get(class_name, 0) + 1
        for child in node.get("inner", []):
            walk(child)

    for cls in module.classes.values():
        for m in cls.methods:
            if m.body_ast:
                walk(m.body_ast)
    for func in module.functions:
        if func.body_ast:
            walk(func.body_ast)

    return counts


def _selector_to_c(selector: str) -> str:
    """Convert an ObjC selector to a C-safe identifier.

    Example: "setPin:color:" -> "setPin_color_"
    """
    return selector.replace(":", "_")


def _base_chain(class_name: str, module: OZModule) -> str:
    """Build 'obj->base.base...' prefix for reaching root fields."""
    cls = module.classes.get(class_name)
    if not cls:
        return "obj->"
    parts = []
    cur = cls
    while cur.superclass and cur.superclass in module.classes:
        parts.append("base.")
        cur = module.classes[cur.superclass]
    prefix = "obj->" + "".join(parts)
    return prefix


def _method_prototype(cls: OZClass, m: OZMethod) -> str:
    # instancetype returns the class's own pointer type
    if m.return_type.raw_qual_type.strip() == "instancetype":
        ret = f"struct {cls.name} *"
    else:
        ret = m.return_type.c_type
    c_sel = _selector_to_c(m.selector)
    params_str = f"struct {cls.name} *self"
    for p in m.params:
        params_str += f", {p.oz_type.c_type} {p.name}"
    return f"{ret} {cls.name}_{c_sel}({params_str})"


def _write_file(path: str, content: str) -> None:
    with open(path, "w") as f:
        f.write(content)
