# SPDX-License-Identifier: Apache-2.0
#
# emit.py - Pass 3: OZModule -> .h/.c files

from __future__ import annotations

import os
from io import StringIO

from .model import DispatchKind, OZClass, OZMethod, OZModule, OZType


def emit(module: OZModule, outdir: str, pool_sizes: dict[str, int] | None = None,
         root_class: str = "OZObject") -> list[str]:
    """Generate C files from OZModule. Returns list of generated file paths."""
    os.makedirs(outdir, exist_ok=True)
    files = []

    files.append(_emit_dispatch_header(module, outdir))
    files.append(_emit_dispatch_source(module, outdir))
    files.extend(_emit_mem_slabs(module, outdir, pool_sizes or {}, root_class))

    for cls in module.classes.values():
        files.append(_emit_class_header(cls, module, outdir, root_class))
        files.append(_emit_class_source(cls, module, outdir, root_class))

    return files


# ---------------------------------------------------------------------------
# oz_dispatch.h
# ---------------------------------------------------------------------------

def _emit_dispatch_header(module: OZModule, outdir: str) -> str:
    out = StringIO()
    out.write("/* Auto-generated by oz_transpile -- do not edit */\n")
    out.write("#pragma once\n\n")
    out.write("#include <stdint.h>\n")
    out.write("#include <stdbool.h>\n\n")
    out.write("#ifndef BOOL\n")
    out.write("#define BOOL _Bool\n")
    out.write("#endif\n\n")

    # Forward declare all class structs
    for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
        out.write(f"struct {cls.name};\n")
    out.write("\n")

    # Class ID enum
    out.write("enum oz_class_id {\n")
    for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
        out.write(f"\tOZ_CLASS_{cls.name} = {cls.class_id},\n")
    out.write(f"\tOZ_CLASS_COUNT = {len(module.classes)}\n")
    out.write("};\n\n")

    # Protocol dispatch macros
    _emit_protocol_macros(module, out)

    path = os.path.join(outdir, "oz_dispatch.h")
    _write_file(path, out.getvalue())
    return path


def _emit_protocol_macros(module: OZModule, out: StringIO) -> None:
    """Generate OZ_SEND macros for protocol-dispatched selectors."""
    # Collect all protocol-dispatched selectors with their signatures
    proto_sels: dict[str, OZMethod] = {}
    for cls in module.classes.values():
        for m in cls.methods:
            if m.dispatch == DispatchKind.PROTOCOL and m.selector not in proto_sels:
                proto_sels[m.selector] = m

    if not proto_sels:
        return

    out.write("/* Protocol dispatch function pointer types */\n")
    for sel, m in sorted(proto_sels.items()):
        c_sel = _selector_to_c(sel)
        ret = m.return_type.c_type
        param_types = ", ".join(
            ["struct OZObject *"] + [p.oz_type.c_type for p in m.params]
        )
        out.write(f"typedef {ret} (*OZ_fn_{c_sel})({param_types});\n")

    out.write("\n/* Protocol dispatch tables (indexed by oz_class_id) */\n")
    for sel, m in sorted(proto_sels.items()):
        c_sel = _selector_to_c(sel)
        out.write(f"extern OZ_fn_{c_sel} OZ_vtable_{c_sel}[OZ_CLASS_COUNT];\n")

    out.write("\n/* OZ_SEND macros */\n")
    for sel, m in sorted(proto_sels.items()):
        c_sel = _selector_to_c(sel)
        param_names = ", ".join(["(obj)"] + [f"({p.name})" for p in m.params])
        arg_list = ", ".join(["obj"] + [p.name for p in m.params])
        macro_params = ", ".join(["obj"] + [p.name for p in m.params])
        out.write(
            f"#define OZ_SEND_{c_sel}({macro_params}) "
            f"OZ_vtable_{c_sel}[((struct OZObject *)(obj))->oz_class_id]"
            f"({param_names})\n"
        )

    out.write("\n/* OZ_PROTOCOL_SEND (cast-free, same as OZ_SEND) */\n")
    for sel, m in sorted(proto_sels.items()):
        c_sel = _selector_to_c(sel)
        macro_params = ", ".join(["obj"] + [p.name for p in m.params])
        out.write(f"#define OZ_PROTOCOL_SEND_{c_sel}({macro_params}) "
                  f"OZ_SEND_{c_sel}({macro_params})\n")

    out.write("\n")


def _emit_dispatch_source(module: OZModule, outdir: str) -> str:
    """Generate oz_dispatch.c with vtable definitions."""
    out = StringIO()
    out.write("/* Auto-generated by oz_transpile -- do not edit */\n")
    out.write("#include \"oz_dispatch.h\"\n\n")

    # Collect all protocol-dispatched selectors
    emitted: set[str] = set()
    for cls in module.classes.values():
        for m in cls.methods:
            if m.dispatch == DispatchKind.PROTOCOL and m.selector not in emitted:
                c_sel = _selector_to_c(m.selector)
                out.write(f"OZ_fn_{c_sel} OZ_vtable_{c_sel}[OZ_CLASS_COUNT];\n")
                emitted.add(m.selector)

    path = os.path.join(outdir, "oz_dispatch.c")
    _write_file(path, out.getvalue())
    return path


# ---------------------------------------------------------------------------
# oz_mem_slabs.h
# ---------------------------------------------------------------------------

def _emit_mem_slabs(module: OZModule, outdir: str,
                    pool_sizes: dict[str, int], root_class: str) -> list[str]:
    """Generate oz_mem_slabs.h (declarations + inline) and oz_mem_slabs.c (definitions)."""
    files = []

    # --- Header ---
    out = StringIO()
    out.write("/* Auto-generated by oz_transpile -- do not edit */\n")
    out.write("#pragma once\n\n")
    out.write("#include <zephyr/kernel.h>\n")
    out.write("#include <string.h>\n\n")

    # Include all class headers so struct types are complete
    for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
        out.write(f"#include \"{cls.name}.h\"\n")
    out.write("\n")

    # Extern declarations for slabs
    for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
        out.write(f"extern struct k_mem_slab oz_slab_{cls.name};\n")
    out.write("\n")

    # Inline alloc/free
    for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
        base_chain = _base_chain(cls.name, module)
        out.write(f"static inline struct {cls.name} *{cls.name}_alloc(void)\n")
        out.write("{\n")
        out.write(f"\tstruct {cls.name} *obj;\n")
        out.write(f"\tif (k_mem_slab_alloc(&oz_slab_{cls.name}, "
                  f"(void **)&obj, K_NO_WAIT) != 0) {{\n")
        out.write(f"\t\treturn (struct {cls.name} *)0;\n")
        out.write("\t}\n")
        out.write(f"\tmemset(obj, 0, sizeof(struct {cls.name}));\n")
        out.write(f"\t{base_chain}oz_class_id = OZ_CLASS_{cls.name};\n")
        out.write(f"\t{base_chain}_refcount = 1;\n")
        out.write("\treturn obj;\n")
        out.write("}\n\n")

        out.write(f"static inline void {cls.name}_free(struct {cls.name} *obj)\n")
        out.write("{\n")
        out.write(f"\tk_mem_slab_free(&oz_slab_{cls.name}, (void *)obj);\n")
        out.write("}\n\n")

    h_path = os.path.join(outdir, "oz_mem_slabs.h")
    _write_file(h_path, out.getvalue())
    files.append(h_path)

    # --- Source ---
    out = StringIO()
    out.write("/* Auto-generated by oz_transpile -- do not edit */\n")
    out.write("#include \"oz_mem_slabs.h\"\n\n")

    for cls in sorted(module.classes.values(), key=lambda c: c.class_id):
        count = pool_sizes.get(cls.name, 4)
        out.write(f"K_MEM_SLAB_DEFINE(oz_slab_{cls.name}, "
                  f"sizeof(struct {cls.name}), {count}, 4);\n")

    c_path = os.path.join(outdir, "oz_mem_slabs.c")
    _write_file(c_path, out.getvalue())
    files.append(c_path)

    return files


# ---------------------------------------------------------------------------
# Per-class .h
# ---------------------------------------------------------------------------

def _emit_class_header(cls: OZClass, module: OZModule, outdir: str,
                       root_class: str) -> str:
    out = StringIO()
    out.write("/* Auto-generated by oz_transpile -- do not edit */\n")
    out.write("#pragma once\n\n")
    out.write("#include \"oz_dispatch.h\"\n")
    if cls.superclass and cls.superclass in module.classes:
        out.write(f"#include \"{cls.superclass}.h\"\n")
    out.write("\n")

    # Struct
    _root_builtins = {"_refcount", "oz_class_id"}
    is_root = not cls.superclass or cls.superclass not in module.classes
    out.write(f"struct {cls.name} {{\n")
    if not is_root:
        out.write(f"\tstruct {cls.superclass} base;\n")
    else:
        out.write("\tuint8_t oz_class_id;\n")
        out.write("\tuint32_t _refcount;\n")
    for ivar in cls.ivars:
        if is_root and ivar.name in _root_builtins:
            continue
        out.write(f"\t{ivar.oz_type.c_type} {ivar.name};\n")
    out.write("};\n\n")

    # Method prototypes
    for m in cls.methods:
        out.write(f"{_method_prototype(cls, m)};\n")
    if cls.methods:
        out.write("\n")

    path = os.path.join(outdir, f"{cls.name}.h")
    _write_file(path, out.getvalue())
    return path


# ---------------------------------------------------------------------------
# Per-class .c
# ---------------------------------------------------------------------------

def _emit_class_source(cls: OZClass, module: OZModule, outdir: str,
                       root_class: str) -> str:
    out = StringIO()
    out.write("/* Auto-generated by oz_transpile -- do not edit */\n")
    out.write(f"#include \"{cls.name}.h\"\n")
    out.write("#include \"oz_mem_slabs.h\"\n")
    if cls.name == root_class:
        out.write("#include <zephyr/sys/atomic.h>\n")
    out.write("\n")

    # Emit retain/release for root class
    if cls.name == root_class:
        _emit_root_retain_release(cls, module, out)

    for m in cls.methods:
        if m.selector in ("retain", "release", "retainCount") and cls.name == root_class:
            continue
        out.write(f"{_method_prototype(cls, m)}\n")
        if m.body_ast:
            _emit_compound_stmt(m.body_ast, out, cls, module, root_class, indent=0)
        else:
            out.write("{\n}\n")
        out.write("\n")

    path = os.path.join(outdir, f"{cls.name}.c")
    _write_file(path, out.getvalue())
    return path


# ---------------------------------------------------------------------------
# Root class retain/release
# ---------------------------------------------------------------------------

def _emit_root_retain_release(cls: OZClass, module: OZModule,
                              out: StringIO) -> None:
    out.write(f"struct {cls.name} *{cls.name}_retain(struct {cls.name} *self)\n")
    out.write("{\n")
    out.write("\tif (self) {\n")
    out.write(f"\t\tatomic_inc((atomic_t *)&self->_refcount);\n")
    out.write("\t}\n")
    out.write("\treturn self;\n")
    out.write("}\n\n")

    out.write(f"void {cls.name}_release(struct {cls.name} *self)\n")
    out.write("{\n")
    out.write("\tif (!self) {\n")
    out.write("\t\treturn;\n")
    out.write("\t}\n")
    out.write(f"\tatomic_val_t old = atomic_dec((atomic_t *)&self->_refcount);\n")
    out.write("\tif (old == 1) {\n")
    out.write(f"\t\tOZ_SEND_dealloc((struct {cls.name} *)self);\n")
    out.write("\t}\n")
    out.write("}\n\n")

    out.write(f"uint32_t {cls.name}_retainCount(struct {cls.name} *self)\n")
    out.write("{\n")
    out.write("\tif (!self) {\n")
    out.write("\t\treturn 0;\n")
    out.write("\t}\n")
    out.write(f"\treturn (uint32_t)atomic_get((atomic_t *)&self->_refcount);\n")
    out.write("}\n\n")


# ---------------------------------------------------------------------------
# Body AST -> C
# ---------------------------------------------------------------------------

def _emit_compound_stmt(node: dict, out: StringIO, cls: OZClass,
                        module: OZModule, root_class: str,
                        indent: int = 0) -> None:
    tabs = "\t" * (indent + 1)
    out.write("\t" * indent + "{\n")
    for child in node.get("inner", []):
        _emit_stmt(child, out, cls, module, root_class, indent + 1)
    out.write("\t" * indent + "}\n")


def _emit_stmt(node: dict, out: StringIO, cls: OZClass, module: OZModule,
               root_class: str, indent: int) -> None:
    tabs = "\t" * indent
    kind = node.get("kind", "")

    if kind == "ReturnStmt":
        inner = node.get("inner", [])
        if inner:
            out.write(f"{tabs}return ")
            _emit_expr(inner[0], out, cls, module, root_class)
            out.write(";\n")
        else:
            out.write(f"{tabs}return;\n")

    elif kind == "DeclStmt":
        for decl in node.get("inner", []):
            if decl.get("kind") == "VarDecl":
                _emit_var_decl(decl, out, cls, module, root_class, indent)

    elif kind == "IfStmt":
        _emit_if_stmt(node, out, cls, module, root_class, indent)

    elif kind == "ForStmt":
        _emit_for_stmt(node, out, cls, module, root_class, indent)

    elif kind == "WhileStmt":
        inner = node.get("inner", [])
        if len(inner) >= 2:
            out.write(f"{tabs}while (")
            _emit_expr(inner[0], out, cls, module, root_class)
            out.write(") ")
            if inner[1].get("kind") == "CompoundStmt":
                _emit_compound_stmt(inner[1], out, cls, module, root_class, indent)
            else:
                out.write("{\n")
                _emit_stmt(inner[1], out, cls, module, root_class, indent + 1)
                out.write(f"{tabs}}}\n")

    elif kind == "CompoundStmt":
        _emit_compound_stmt(node, out, cls, module, root_class, indent)

    elif kind == "NullStmt":
        out.write(f"{tabs};\n")

    elif kind == "BreakStmt":
        out.write(f"{tabs}break;\n")

    elif kind == "ContinueStmt":
        out.write(f"{tabs}continue;\n")

    elif kind == "CompoundAssignOperator":
        out.write(tabs)
        _emit_expr(node, out, cls, module, root_class)
        out.write(";\n")

    else:
        # Expression statement
        out.write(tabs)
        _emit_expr(node, out, cls, module, root_class)
        out.write(";\n")


def _emit_var_decl(node: dict, out: StringIO, cls: OZClass, module: OZModule,
                   root_class: str, indent: int) -> None:
    tabs = "\t" * indent
    qt = node.get("type", {}).get("qualType", "int")
    oz_type = OZType(qt)
    name = node.get("name", "_anon")
    c_type = oz_type.c_type

    inner = node.get("inner", [])
    init_expr = None
    for child in inner:
        if child.get("kind") not in ("FullComment",):
            init_expr = child
            break

    if init_expr:
        out.write(f"{tabs}{c_type} {name} = ")
        _emit_expr(init_expr, out, cls, module, root_class)
        out.write(";\n")
    else:
        out.write(f"{tabs}{c_type} {name};\n")


def _emit_if_stmt(node: dict, out: StringIO, cls: OZClass, module: OZModule,
                  root_class: str, indent: int) -> None:
    tabs = "\t" * indent
    inner = node.get("inner", [])
    if not inner:
        return

    has_else = node.get("hasElse", False)

    # Clang AST: inner[0]=cond, inner[1]=then, [inner[2]=else]
    cond = inner[0]
    then_body = inner[1] if len(inner) > 1 else None
    else_body = inner[2] if has_else and len(inner) > 2 else None

    out.write(f"{tabs}if (")
    _emit_expr(cond, out, cls, module, root_class)
    out.write(") ")
    if then_body:
        if then_body.get("kind") == "CompoundStmt":
            _emit_compound_stmt(then_body, out, cls, module, root_class, indent)
        else:
            out.write("{\n")
            _emit_stmt(then_body, out, cls, module, root_class, indent + 1)
            out.write(f"{tabs}}}\n")

    if else_body:
        if else_body.get("kind") == "IfStmt":
            out.write(f"{tabs}else ")
            _emit_if_stmt(else_body, out, cls, module, root_class, indent)
        elif else_body.get("kind") == "CompoundStmt":
            out.write(f"{tabs}else ")
            _emit_compound_stmt(else_body, out, cls, module, root_class, indent)
        else:
            out.write(f"{tabs}else {{\n")
            _emit_stmt(else_body, out, cls, module, root_class, indent + 1)
            out.write(f"{tabs}}}\n")


def _emit_for_stmt(node: dict, out: StringIO, cls: OZClass, module: OZModule,
                   root_class: str, indent: int) -> None:
    tabs = "\t" * indent
    inner = node.get("inner", [])
    # Clang ForStmt: inner = [init, condVar, cond, inc, body]
    # but null entries may be missing, padded with NullStmt or absent
    # We need exactly the right slots
    if len(inner) < 2:
        return

    out.write(f"{tabs}for (")
    # init
    if len(inner) > 0 and inner[0].get("kind") not in ("NullStmt", "<<<NULL>>>"):
        if inner[0].get("kind") == "DeclStmt":
            decls = inner[0].get("inner", [])
            if decls and decls[0].get("kind") == "VarDecl":
                vd = decls[0]
                qt = vd.get("type", {}).get("qualType", "int")
                vname = vd.get("name", "i")
                c_type = OZType(qt).c_type
                vinit = [c for c in vd.get("inner", []) if c.get("kind") != "FullComment"]
                out.write(f"{c_type} {vname}")
                if vinit:
                    out.write(" = ")
                    _emit_expr(vinit[0], out, cls, module, root_class)
        else:
            _emit_expr(inner[0], out, cls, module, root_class)
    out.write("; ")

    # cond (index 2 in Clang AST; index 1 might be condVar)
    cond_idx = 2 if len(inner) > 4 else 1
    if cond_idx < len(inner) and inner[cond_idx].get("kind") not in ("NullStmt", "<<<NULL>>>"):
        _emit_expr(inner[cond_idx], out, cls, module, root_class)
    out.write("; ")

    # inc
    inc_idx = 3 if len(inner) > 4 else 2
    if inc_idx < len(inner) and inner[inc_idx].get("kind") not in ("NullStmt", "<<<NULL>>>"):
        _emit_expr(inner[inc_idx], out, cls, module, root_class)
    out.write(") ")

    # body
    body_idx = 4 if len(inner) > 4 else len(inner) - 1
    body = inner[body_idx] if body_idx < len(inner) else None
    if body and body.get("kind") == "CompoundStmt":
        _emit_compound_stmt(body, out, cls, module, root_class, indent)
    elif body:
        out.write("{\n")
        _emit_stmt(body, out, cls, module, root_class, indent + 1)
        out.write(f"{tabs}}}\n")
    else:
        out.write("{}\n")


def _emit_expr(node: dict, out: StringIO, cls: OZClass, module: OZModule,
               root_class: str) -> None:
    kind = node.get("kind", "")

    if kind == "ImplicitCastExpr":
        inner = node.get("inner", [])
        if inner:
            _emit_expr(inner[0], out, cls, module, root_class)
        return

    if kind == "CStyleCastExpr":
        qt = node.get("type", {}).get("qualType", "")
        out.write(f"({OZType(qt).c_type})")
        inner = node.get("inner", [])
        if inner:
            _emit_expr(inner[0], out, cls, module, root_class)
        return

    if kind == "ParenExpr":
        out.write("(")
        inner = node.get("inner", [])
        if inner:
            _emit_expr(inner[0], out, cls, module, root_class)
        out.write(")")
        return

    if kind == "ObjCMessageExpr":
        _emit_msg_expr(node, out, cls, module, root_class)
        return

    if kind == "ObjCIvarRefExpr":
        ivar_name = node.get("decl", {}).get("name", "")
        out.write(f"self->{ivar_name}")
        return

    if kind == "DeclRefExpr":
        name = node.get("referencedDecl", {}).get("name", "")
        out.write(name)
        return

    if kind == "MemberExpr":
        inner = node.get("inner", [])
        member = node.get("name", "")
        is_arrow = node.get("isArrow", False)
        if inner:
            _emit_expr(inner[0], out, cls, module, root_class)
        out.write(f"->{member}" if is_arrow else f".{member}")
        return

    if kind == "BinaryOperator":
        inner = node.get("inner", [])
        op = node.get("opcode", "")
        if len(inner) == 2:
            _emit_expr(inner[0], out, cls, module, root_class)
            out.write(f" {op} ")
            _emit_expr(inner[1], out, cls, module, root_class)
        return

    if kind == "CompoundAssignOperator":
        inner = node.get("inner", [])
        op = node.get("opcode", "")
        if len(inner) == 2:
            _emit_expr(inner[0], out, cls, module, root_class)
            out.write(f" {op} ")
            _emit_expr(inner[1], out, cls, module, root_class)
        return

    if kind == "UnaryOperator":
        inner = node.get("inner", [])
        op = node.get("opcode", "")
        is_postfix = node.get("isPostfix", False)
        if inner:
            if is_postfix:
                _emit_expr(inner[0], out, cls, module, root_class)
                out.write(op)
            else:
                out.write(op)
                _emit_expr(inner[0], out, cls, module, root_class)
        return

    if kind == "ConditionalOperator":
        inner = node.get("inner", [])
        if len(inner) == 3:
            _emit_expr(inner[0], out, cls, module, root_class)
            out.write(" ? ")
            _emit_expr(inner[1], out, cls, module, root_class)
            out.write(" : ")
            _emit_expr(inner[2], out, cls, module, root_class)
        return

    if kind == "IntegerLiteral":
        out.write(node.get("value", "0"))
        return

    if kind == "FloatingLiteral":
        out.write(node.get("value", "0.0"))
        return

    if kind == "CharacterLiteral":
        val = node.get("value", 0)
        if 32 <= val < 127 and val != ord("'") and val != ord("\\"):
            out.write(f"'{chr(val)}'")
        else:
            out.write(str(val))
        return

    if kind == "StringLiteral":
        out.write(node.get("value", '""'))
        return

    if kind == "ObjCStringLiteral":
        inner = node.get("inner", [])
        if inner:
            out.write(inner[0].get("value", '""'))
        return

    if kind == "ObjCBoolLiteralExpr":
        val = node.get("value", False)
        if isinstance(val, str):
            out.write("0" if "no" in val.lower() else "1")
        else:
            out.write("1" if val else "0")
        return

    if kind == "GNUNullExpr" or kind == "CXXNullPtrLiteralExpr":
        out.write("((void *)0)")
        return

    if kind == "PseudoObjectExpr":
        # Property access — emit the getter/setter call
        inner = node.get("inner", [])
        if inner:
            _emit_expr(inner[0], out, cls, module, root_class)
        return

    if kind == "OpaqueValueExpr":
        inner = node.get("inner", [])
        if inner:
            _emit_expr(inner[0], out, cls, module, root_class)
        return

    if kind == "CallExpr":
        inner = node.get("inner", [])
        if inner:
            _emit_expr(inner[0], out, cls, module, root_class)
            out.write("(")
            args = inner[1:]
            for i, arg in enumerate(args):
                if i > 0:
                    out.write(", ")
                _emit_expr(arg, out, cls, module, root_class)
            out.write(")")
        return

    if kind == "ArraySubscriptExpr":
        inner = node.get("inner", [])
        if len(inner) == 2:
            _emit_expr(inner[0], out, cls, module, root_class)
            out.write("[")
            _emit_expr(inner[1], out, cls, module, root_class)
            out.write("]")
        return

    # Fallback: try inner children or emit placeholder
    inner = node.get("inner", [])
    if inner:
        _emit_expr(inner[0], out, cls, module, root_class)
    else:
        out.write(f"/* TODO: {kind} */")


def _emit_msg_expr(node: dict, out: StringIO, cls: OZClass, module: OZModule,
                   root_class: str) -> None:
    selector = node.get("selector", "")
    c_sel = _selector_to_c(selector)
    receiver_kind = node.get("receiverKind", "")
    inner = node.get("inner", [])

    # [super sel] -> ParentClass_sel((struct ParentClass *)self)
    # Super calls have no receiver in inner — all children are args
    if receiver_kind.startswith("super"):
        parent = cls.superclass or root_class
        # Look up return type to decide if cast is needed
        ret_type = node.get("type", {}).get("qualType", "void")
        needs_cast = OZType(ret_type).is_object
        if needs_cast:
            out.write(f"(struct {cls.name} *)")
        out.write(f"{parent}_{c_sel}(")
        out.write(f"(struct {parent} *)self")
        for arg in inner:
            out.write(", ")
            _emit_expr(arg, out, cls, module, root_class)
        out.write(")")
        return

    # [ClassName alloc] -> ClassName_alloc()
    if receiver_kind == "class":
        class_type = node.get("classType", {}).get("qualType", "")
        # Class messages: all inner children are args (no receiver)
        out.write(f"{class_type}_{c_sel}(")
        for i, arg in enumerate(inner):
            if i > 0:
                out.write(", ")
            _emit_expr(arg, out, cls, module, root_class)
        out.write(")")
        return

    # [obj sel] -> check dispatch kind
    # Instance messages: inner[0] is receiver, rest are args
    args_exprs = _collect_msg_args(inner)
    receiver = inner[0] if inner else None

    # Look up dispatch kind
    dispatch = _find_dispatch_kind(selector, module)
    if dispatch == DispatchKind.PROTOCOL:
        out.write(f"OZ_SEND_{c_sel}(")
        if receiver:
            _emit_expr(receiver, out, cls, module, root_class)
        for arg in args_exprs:
            out.write(", ")
            _emit_expr(arg, out, cls, module, root_class)
        out.write(")")
    else:
        # Static dispatch: infer receiver class from type
        recv_class = _infer_receiver_class(receiver, cls) if receiver else cls.name
        out.write(f"{recv_class}_{c_sel}(")
        if receiver:
            _emit_expr(receiver, out, cls, module, root_class)
        for arg in args_exprs:
            out.write(", ")
            _emit_expr(arg, out, cls, module, root_class)
        out.write(")")


def _collect_msg_args(inner: list[dict]) -> list[dict]:
    """Extract argument expressions from ObjCMessageExpr inner nodes.

    inner[0] is the receiver, the rest are arguments.
    """
    if len(inner) <= 1:
        return []
    return inner[1:]


def _find_dispatch_kind(selector: str, module: OZModule) -> DispatchKind:
    for cls in module.classes.values():
        for m in cls.methods:
            if m.selector == selector:
                return m.dispatch
    return DispatchKind.STATIC


def _infer_receiver_class(node: dict, cls: OZClass) -> str:
    """Best-effort receiver class from AST type info."""
    qt = node.get("type", {}).get("qualType", "")
    oz = OZType(qt)
    if oz.is_object:
        name = oz._strip_qualifiers().rstrip(" *")
        if name and name not in ("id", "instancetype"):
            return name
    return cls.name


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _selector_to_c(selector: str) -> str:
    """Convert an ObjC selector to a C-safe identifier.

    Example: "setPin:color:" -> "setPin_color_"
    """
    return selector.replace(":", "_")


def _base_chain(class_name: str, module: OZModule) -> str:
    """Build 'obj->base.base...' prefix for reaching root fields."""
    cls = module.classes.get(class_name)
    if not cls:
        return "obj->"
    parts = []
    cur = cls
    while cur.superclass and cur.superclass in module.classes:
        parts.append("base.")
        cur = module.classes[cur.superclass]
    prefix = "obj->" + "".join(parts)
    return prefix


def _method_prototype(cls: OZClass, m: OZMethod) -> str:
    # instancetype returns the class's own pointer type
    if m.return_type.raw_qual_type.strip() == "instancetype":
        ret = f"struct {cls.name} *"
    else:
        ret = m.return_type.c_type
    c_sel = _selector_to_c(m.selector)
    params_str = f"struct {cls.name} *self"
    for p in m.params:
        params_str += f", {p.oz_type.c_type} {p.name}"
    return f"{ret} {cls.name}_{c_sel}({params_str})"


def _write_file(path: str, content: str) -> None:
    with open(path, "w") as f:
        f.write(content)
