/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include <stdint.h>
#include <stdbool.h>

#ifndef BOOL
#define BOOL _Bool
#endif

struct OZObject;
struct Animal;
struct Dog;

typedef struct OZObject *id;

enum oz_class_id {
	OZ_CLASS_OZObject = 0,
	OZ_CLASS_Animal = 1,
	OZ_CLASS_Dog = 2,
	OZ_CLASS_COUNT = 3
};

/* Class introspection tables */
extern const char *const oz_class_names[OZ_CLASS_COUNT];
extern const uint8_t oz_superclass_id[OZ_CLASS_COUNT];

static inline const char *oz_name(uint8_t class_id)
{
	return oz_class_names[class_id];
}

static inline uint8_t oz_superclass(uint8_t class_id)
{
	return oz_superclass_id[class_id];
}

static inline bool oz_isKindOfClass(uint8_t class_id, uint8_t target_class_id)
{
	uint8_t cur = class_id;
	while (cur != OZ_CLASS_COUNT) {
		if (cur == target_class_id) {
			return true;
		}
		cur = oz_superclass_id[cur];
	}
	return false;
}

/* Protocol dispatch function pointer types */
typedef void (*OZ_fn_dealloc)(struct OZObject *);
typedef struct OZObject * (*OZ_fn_init)(struct OZObject *);

/* Compile-time dispatch: OZ_IMPL macros map class x selector -> direct function */
#define OZ_IMPL_OZObject_dealloc(self, ...)	OZObject_dealloc((struct OZObject *)(self), ##__VA_ARGS__)
#define OZ_IMPL_Animal_dealloc(self, ...)	Animal_dealloc((struct Animal *)(self), ##__VA_ARGS__)
#define OZ_IMPL_Dog_dealloc(self, ...)	Dog_dealloc((struct Dog *)(self), ##__VA_ARGS__)
#define OZ_IMPL_OZObject_init(self, ...)	OZObject_init((struct OZObject *)(self), ##__VA_ARGS__)
#define OZ_IMPL_Animal_init(self, ...)	OZObject_init((struct OZObject *)(self), ##__VA_ARGS__)
#define OZ_IMPL_Dog_init(self, ...)	OZObject_init((struct OZObject *)(self), ##__VA_ARGS__)

/* Static dispatch: token concatenation resolves at compile time */
#define OZ_SEND(cls, sel, self, ...) OZ_IMPL_##cls##_##sel((self), ##__VA_ARGS__)

/* Const protocol dispatch tables (indexed by oz_class_id) */
extern const OZ_fn_dealloc OZ_PROTOCOL_RESOLVE_dealloc[OZ_CLASS_COUNT];
extern const OZ_fn_init OZ_PROTOCOL_RESOLVE_init[OZ_CLASS_COUNT];

/* OZ_PROTOCOL_SEND macros — polymorphic fallback, caller must ensure obj has no side effects */
#define OZ_PROTOCOL_SEND_dealloc(obj) OZ_PROTOCOL_RESOLVE_dealloc[((struct OZObject *)(obj))->oz_class_id]((struct OZObject *)(obj))
#define OZ_PROTOCOL_SEND_init(obj) OZ_PROTOCOL_RESOLVE_init[((struct OZObject *)(obj))->oz_class_id]((struct OZObject *)(obj))


void OZObject_dispatch_free(struct OZObject *obj);

/* OZLog — formatted logging with %@ object support */
void OZLog(const char *fmt, ...);
