/* Auto-generated by oz_transpile -- do not edit */
#include "oz_dispatch.h"
#include "OZObject_ozh.h"
#include "Animal_ozh.h"
#include "Dog_ozh.h"

const char *const oz_class_names[OZ_CLASS_COUNT] = {
	[OZ_CLASS_OZObject] = "OZObject",
	[OZ_CLASS_Animal] = "Animal",
	[OZ_CLASS_Dog] = "Dog",
};

const uint8_t oz_superclass_id[OZ_CLASS_COUNT] = {
	[OZ_CLASS_OZObject] = OZ_CLASS_COUNT,
	[OZ_CLASS_Animal] = OZ_CLASS_OZObject,
	[OZ_CLASS_Dog] = OZ_CLASS_Animal,
};

void OZObject_dispatch_free(struct OZObject *obj)
{
	switch (obj->oz_class_id) {
	case OZ_CLASS_OZObject: OZObject_free((struct OZObject *)obj); break;
	case OZ_CLASS_Animal: Animal_free((struct Animal *)obj); break;
	case OZ_CLASS_Dog: Dog_free((struct Dog *)obj); break;
	default: break;
	}
}
