/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "platform/oz_platform.h"
#include "oz_dispatch.h"
#include "OZObject_ozh.h"

struct Color {
	struct OZObject base;
	int _red;
	int _green;
	int _blue;
};

struct Color * Color_initWithRed_green_blue_(struct Color *self, int r, int g, int b);
int Color_red(struct Color *self);
void Color_dealloc(struct Color *self);

