/* Auto-generated by oz_transpile -- do not edit */
#include "Color_ozh.h"
#include "OZObject_ozh.h"

OZ_SLAB_DEFINE(oz_slab_Color, sizeof(struct Color), 1, 4);

struct Color * Color_initWithRed_green_blue_(struct Color *self, int r, int g, int b)
{
	(struct Color *)OZObject_init((struct OZObject *)self);
	self->_red = r;
	self->_green = g;
	self->_blue = b;
	return self;
}
int Color_red(struct Color *self)
{
	return self->_red;
}
void Color_dealloc(struct Color *self)
{
	OZObject_dealloc((struct OZObject *)self);
}
