/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "platform/oz_platform.h"
#include "oz_dispatch.h"
#include <string.h>

#include "OZObject_ozh.h"
#include "Color_ozh.h"

extern oz_slab_t oz_slab_OZObject;
extern oz_slab_t oz_slab_Color;

static inline struct OZObject *OZObject_alloc(void)
{
	struct OZObject *obj;
	if (oz_slab_alloc(&oz_slab_OZObject, (void **)&obj) != 0) {
		return (struct OZObject *)0;
	}
	memset(obj, 0, sizeof(struct OZObject));
	obj->oz_class_id = OZ_CLASS_OZObject;
	oz_atomic_init(&obj->_refcount, 1);
	return obj;
}

static inline void OZObject_free(struct OZObject *obj)
{
	oz_slab_free(&oz_slab_OZObject, (void *)obj);
}

static inline struct Color *Color_alloc(void)
{
	struct Color *obj;
	if (oz_slab_alloc(&oz_slab_Color, (void **)&obj) != 0) {
		return (struct Color *)0;
	}
	memset(obj, 0, sizeof(struct Color));
	obj->base.oz_class_id = OZ_CLASS_Color;
	oz_atomic_init(&obj->base._refcount, 1);
	return obj;
}

static inline void Color_free(struct Color *obj)
{
	oz_slab_free(&oz_slab_Color, (void *)obj);
}

static inline void OZObject_dispatch_free(struct OZObject *obj)
{
	switch (obj->oz_class_id) {
	case OZ_CLASS_OZObject: OZObject_free((struct OZObject *)obj); break;
	case OZ_CLASS_Color: Color_free((struct Color *)obj); break;
	default: break;
	}
}

