// SPDX-License-Identifier: Apache-2.0
//
// behavior_foundation_array.rs - OZ-092 Foundation work: OZArray, ported
// from tests/behavior/cases/foundation/array_basic.m and
// tests/behavior/cases/inline/array_fast_access.m.
//
// Uses the real `OZObject` (`common::ozobject_src`) as the root class,
// `OZQ31` (`common::ozq31_src`) for the boxed integer elements, and
// `OZArray` (`common::ozarray_src`, a partial port -- see its doc comment
// for what's deliberately left out and why). The interesting part isn't
// the class -- it's how `@[...]` desugars: `emit::render_boxed_array_literal`
// builds a `void *` stack buffer from the (retained-or-fresh, per
// `emit::is_fresh_alloc`) element references, then calls the malloc-based
// `OZArray_oz_initWithItems` builder generated by
// `companion::render_array_support`. Only `OZObject`, `OZQ31`, and
// `OZArray` fixtures were ported -- OZMutableString/OZDictionary and
// for-in loops are separate, not-yet-started OZ-092 checklist items.

mod common;
use common::{compile_and_run, ozarray_src, ozobject_src as PREAMBLE, ozq31_src};

#[test]
fn array_basic_literal_count_first_element_and_out_of_bounds() {
    // array_basic.m: literalCount (count of a 3-element literal),
    // firstElement (objectAtIndex: 0, unboxed via intValue), outOfBoundsNil
    // (objectAtIndex: past the end returns nil).
    let src = format!(
        "{}{}{}\n\
@interface ArrayTest : OZObject
- (unsigned int)literalCount;
- (int)firstElement;
- (BOOL)outOfBoundsNil;
@end

@implementation ArrayTest
- (unsigned int)literalCount {{
	OZArray *arr = @[@(1), @(2), @(3)];
	size_t c = [arr count];
	return c;
}}
- (int)firstElement {{
	OZArray *arr = @[@(42), @(7)];
	OZQ31 *n = [arr objectAtIndex:0];
	int v = [n intValue];
	return v;
}}
- (BOOL)outOfBoundsNil {{
	OZArray *arr = @[@(1)];
	id obj = [arr objectAtIndex:99];
	return obj == nil;
}}
@end

#include <stdio.h>
int main(void) {{
	ArrayTest *t = [ArrayTest alloc];
	printf(\"count=%zu\\n\", [t literalCount]);
	printf(\"first=%d\\n\", [t firstElement]);
	printf(\"oob=%d\\n\", [t outOfBoundsNil]);
	return 0;
}}
",
        PREAMBLE(), ozq31_src(), ozarray_src()
    );
    let stdout = compile_and_run(&src, "array_basic_literal_count_first_element_and_out_of_bounds");
    assert_eq!(stdout, "count=3\nfirst=42\noob=1\n");
}

#[test]
fn array_fast_access_count_and_first_val() {
    // array_fast_access.m: stores count/first-value into ivars during
    // -run, read back through separate accessors -- exercises the boxed
    // array literal's `objectAtIndex:` result surviving past the method
    // that created it.
    let src = format!(
        "{}{}{}\n\
@interface ArrayAccessTest : OZObject {{
	size_t _count;
	int _firstVal;
}}
- (void)run;
- (size_t)count;
- (int)firstVal;
@end

@implementation ArrayAccessTest
- (void)run {{
	OZArray *arr = @[@(100), @(200), @(300)];
	_count = [arr count];
	OZQ31 *first = [arr objectAtIndex:0];
	_firstVal = [first intValue];
}}
- (size_t)count {{
	return _count;
}}
- (int)firstVal {{
	return _firstVal;
}}
@end

#include <stdio.h>
int main(void) {{
	ArrayAccessTest *t = [ArrayAccessTest alloc];
	[t run];
	printf(\"count=%zu\\n\", [t count]);
	printf(\"first=%d\\n\", [t firstVal]);
	return 0;
}}
",
        PREAMBLE(), ozq31_src(), ozarray_src()
    );
    let stdout = compile_and_run(&src, "array_fast_access_count_and_first_val");
    assert_eq!(stdout, "count=3\nfirst=100\n");
}

/// `-cDescription:maxLength:` used to be cut from the fixture because its
/// body recurses `[elem cDescription:...]` on a bare `id` element. That
/// resolves now (the selector is always dynamically dispatched, so the
/// element's real class picks the implementation at runtime), and this
/// exercises it end to end: the rendering is OZArray's own parenthesised
/// comma list, with each element rendered by OZQ31's override.
#[test]
fn array_cdescription_recurses_into_elements() {
    let src = format!(
        "{}{}{}\n{}",
        PREAMBLE(),
        ozq31_src(),
        ozarray_src(),
        "\
#include <stdio.h>
int main(void) {
	OZArray *nums = @[ @1, @2, @3 ];
	char buf[64];
	int n = [nums cDescription:buf maxLength:63];
	buf[n] = 0;
	printf(\"desc=%s\\n\", buf);
	printf(\"len=%d\\n\", n);
	[nums release];
	return 0;
}
"
    );
    let stdout = compile_and_run(&src, "array_cdescription_recurses_into_elements");
    assert_eq!(stdout, "desc=(1, 2, 3)\nlen=9\n");
}

/// `-enumerateObjectsUsingBlock:` was cut too. It needs a block-typed
/// parameter lowered to a plain function pointer
/// (`collect::detect_block_param_type`) and a non-capturing block literal
/// hoisted to a static function (`emit::render_block`) at the call site.
/// The `BOOL *stop` out-parameter is what makes early termination
/// observable, so it is asserted rather than just the full walk.
#[test]
fn array_enumerate_objects_using_block() {
    let src = format!(
        "{}{}{}\n{}",
        PREAMBLE(),
        ozq31_src(),
        ozarray_src(),
        "\
static int g_sum = 0;
static int g_calls = 0;

#include <stdio.h>
int main(void) {
	OZArray *nums = @[ @10, @20, @30 ];
	[nums enumerateObjectsUsingBlock:^(id obj, size_t idx, BOOL *stop) {
		g_calls = g_calls + 1;
		g_sum = g_sum + [((OZQ31 *)obj) int32Value];
	}];
	printf(\"calls=%d\\n\", g_calls);
	printf(\"sum=%d\\n\", g_sum);

	g_calls = 0;
	[nums enumerateObjectsUsingBlock:^(id obj, size_t idx, BOOL *stop) {
		g_calls = g_calls + 1;
		if (idx == 1) {
			*stop = 1;
		}
	}];
	printf(\"calls_until_stop=%d\\n\", g_calls);
	[nums release];
	return 0;
}
"
    );
    let stdout = compile_and_run(&src, "array_enumerate_objects_using_block");
    assert_eq!(stdout, "calls=3\nsum=60\ncalls_until_stop=2\n");
}
