// SPDX-License-Identifier: Apache-2.0
//
// behavior_foundation_array.rs - OZ-092 Foundation work: OZArray, ported
// from tests/behavior/cases/foundation/array_basic.m and
// tests/behavior/cases/inline/array_fast_access.m.
//
// Uses the real `OZObject` (`common::ozobject_src`) as the root class,
// `OZQ31` (`common::ozq31_src`) for the boxed integer elements, and
// `OZArray` (`common::ozarray_src`, a partial port -- see its doc comment
// for what's deliberately left out and why). The interesting part isn't
// the class -- it's how `@[...]` desugars: `emit::render_boxed_array_literal`
// builds a `void *` stack buffer from the (retained-or-fresh, per
// `emit::is_fresh_alloc`) element references, then calls the malloc-based
// `OZArray_oz_initWithItems` builder generated by
// `companion::render_array_support`. Only `OZObject`, `OZQ31`, and
// `OZArray` fixtures were ported -- OZMutableString/OZDictionary and
// for-in loops are separate, not-yet-started OZ-092 checklist items.

mod common;
use common::{compile_and_run, ozarray_src, ozobject_src as PREAMBLE, ozq31_src};

#[test]
fn array_basic_literal_count_first_element_and_out_of_bounds() {
    // array_basic.m: literalCount (count of a 3-element literal),
    // firstElement (objectAtIndex: 0, unboxed via intValue), outOfBoundsNil
    // (objectAtIndex: past the end returns nil).
    let src = format!(
        "{}{}{}\n\
@interface ArrayTest : OZObject
- (unsigned int)literalCount;
- (int)firstElement;
- (BOOL)outOfBoundsNil;
@end

@implementation ArrayTest
- (unsigned int)literalCount {{
	OZArray *arr = @[@(1), @(2), @(3)];
	unsigned int c = [arr count];
	return c;
}}
- (int)firstElement {{
	OZArray *arr = @[@(42), @(7)];
	OZQ31 *n = [arr objectAtIndex:0];
	int v = [n intValue];
	return v;
}}
- (BOOL)outOfBoundsNil {{
	OZArray *arr = @[@(1)];
	id obj = [arr objectAtIndex:99];
	return obj == nil;
}}
@end

#include <stdio.h>
int main(void) {{
	ArrayTest *t = [ArrayTest alloc];
	printf(\"count=%u\\n\", [t literalCount]);
	printf(\"first=%d\\n\", [t firstElement]);
	printf(\"oob=%d\\n\", [t outOfBoundsNil]);
	return 0;
}}
",
        PREAMBLE(), ozq31_src(), ozarray_src()
    );
    let stdout = compile_and_run(&src, "array_basic_literal_count_first_element_and_out_of_bounds");
    assert_eq!(stdout, "count=3\nfirst=42\noob=1\n");
}

#[test]
fn array_fast_access_count_and_first_val() {
    // array_fast_access.m: stores count/first-value into ivars during
    // -run, read back through separate accessors -- exercises the boxed
    // array literal's `objectAtIndex:` result surviving past the method
    // that created it.
    let src = format!(
        "{}{}{}\n\
@interface ArrayAccessTest : OZObject {{
	unsigned int _count;
	int _firstVal;
}}
- (void)run;
- (unsigned int)count;
- (int)firstVal;
@end

@implementation ArrayAccessTest
- (void)run {{
	OZArray *arr = @[@(100), @(200), @(300)];
	_count = [arr count];
	OZQ31 *first = [arr objectAtIndex:0];
	_firstVal = [first intValue];
}}
- (unsigned int)count {{
	return _count;
}}
- (int)firstVal {{
	return _firstVal;
}}
@end

#include <stdio.h>
int main(void) {{
	ArrayAccessTest *t = [ArrayAccessTest alloc];
	[t run];
	printf(\"count=%u\\n\", [t count]);
	printf(\"first=%d\\n\", [t firstVal]);
	return 0;
}}
",
        PREAMBLE(), ozq31_src(), ozarray_src()
    );
    let stdout = compile_and_run(&src, "array_fast_access_count_and_first_val");
    assert_eq!(stdout, "count=3\nfirst=100\n");
}
