# SPDX-License-Identifier: Apache-2.0
#
# test_roundtrip.py - Round-trip integration test for the extract→context→render
# pipeline (patched source path for user classes).

from __future__ import annotations

import difflib
import json
import tempfile
from pathlib import Path

import pytest

from oz_transpile.collect import collect
from oz_transpile.emit import emit
from oz_transpile.resolve import resolve

FIXTURES = Path(__file__).parent / "fixtures"


def _normalize(text: str) -> str:
    """Strip trailing whitespace per line, ensure single trailing newline."""
    lines = [line.rstrip() for line in text.splitlines()]
    return "\n".join(lines) + "\n"


def _load_ast(fixture_source: Path) -> dict:
    """Load AST JSON and patch __FIXTURE__ loc to point to actual source."""
    ast_path = fixture_source.with_suffix(".ast.json")
    with open(ast_path) as f:
        ast = json.load(f)
    source_str = str(fixture_source)
    for node in ast.get("inner", []):
        loc = node.get("loc", {})
        if loc.get("file") == "__FIXTURE__":
            loc["file"] = source_str
    return ast


class TestRoundTrip:
    """End-to-end test: .m fixture + AST → collect → resolve → emit (patched source)."""

    def test_patched_source_output(self):
        """Full pipeline produces expected C output for OZBlinky."""
        source = FIXTURES / "extract_basic.m"
        ast = _load_ast(source)

        module = collect(ast)
        module.source_stem = "OZBlinky"
        module.source_paths["OZBlinky"] = module.source_path

        resolve(module)

        with tempfile.TemporaryDirectory() as tmpdir:
            files = emit(module, tmpdir)

            blinky_c = Path(tmpdir) / "OZBlinky_ozm.c"
            assert blinky_c.exists(), "OZBlinky_ozm.c not generated"

            actual = _normalize(blinky_c.read_text())
            expected_path = FIXTURES / "expected_roundtrip_OZBlinky_ozm.c"
            expected = _normalize(expected_path.read_text())

            if actual != expected:
                diff = list(difflib.unified_diff(
                    expected.splitlines(keepends=True),
                    actual.splitlines(keepends=True),
                    fromfile="expected",
                    tofile="actual",
                ))
                pytest.fail("OZBlinky_ozm.c mismatch:\n" + "".join(diff))

    def test_source_comments_preserved(self):
        """Comments between methods survive the extract→render pipeline."""
        source = FIXTURES / "extract_basic.m"
        ast = _load_ast(source)

        module = collect(ast)
        module.source_stem = "OZBlinky"
        module.source_paths["OZBlinky"] = module.source_path

        resolve(module)

        with tempfile.TemporaryDirectory() as tmpdir:
            emit(module, tmpdir)
            content = (Path(tmpdir) / "OZBlinky_ozm.c").read_text()

            assert "/* Initialize the blinky LED */" in content
            assert "/* Toggle the LED state */" in content

    def test_preamble_structure(self):
        """Preamble has auto-generated header, include, and slab define."""
        source = FIXTURES / "extract_basic.m"
        ast = _load_ast(source)

        module = collect(ast)
        module.source_stem = "OZBlinky"
        module.source_paths["OZBlinky"] = module.source_path

        resolve(module)

        with tempfile.TemporaryDirectory() as tmpdir:
            emit(module, tmpdir)
            content = (Path(tmpdir) / "OZBlinky_ozm.c").read_text()

            assert content.startswith("/* Auto-generated by oz_transpile")
            assert '#include "OZBlinky_ozh.h"' in content
            assert "OZ_SLAB_DEFINE(oz_slab_OZBlinky" in content

    def test_interface_replaced_with_comment(self):
        """@interface block replaced with header reference comment."""
        source = FIXTURES / "extract_basic.m"
        ast = _load_ast(source)

        module = collect(ast)
        module.source_stem = "OZBlinky"
        module.source_paths["OZBlinky"] = module.source_path

        resolve(module)

        with tempfile.TemporaryDirectory() as tmpdir:
            emit(module, tmpdir)
            content = (Path(tmpdir) / "OZBlinky_ozm.c").read_text()

            assert "/* @interface OZBlinky" in content
            # No raw @interface outside of comments
            for line in content.splitlines():
                stripped = line.strip()
                if stripped.startswith("@interface"):
                    pytest.fail(f"Raw @interface found: {line}")

    def test_import_removed(self):
        """#import <Foundation/Foundation.h> is removed."""
        source = FIXTURES / "extract_basic.m"
        ast = _load_ast(source)

        module = collect(ast)
        module.source_stem = "OZBlinky"
        module.source_paths["OZBlinky"] = module.source_path

        resolve(module)

        with tempfile.TemporaryDirectory() as tmpdir:
            emit(module, tmpdir)
            content = (Path(tmpdir) / "OZBlinky_ozm.c").read_text()

            assert "#import" not in content

    def test_auto_dealloc_emitted(self):
        """Auto-dealloc is generated for OZBlinky."""
        source = FIXTURES / "extract_basic.m"
        ast = _load_ast(source)

        module = collect(ast)
        module.source_stem = "OZBlinky"
        module.source_paths["OZBlinky"] = module.source_path

        resolve(module)

        with tempfile.TemporaryDirectory() as tmpdir:
            emit(module, tmpdir)
            content = (Path(tmpdir) / "OZBlinky_ozm.c").read_text()

            assert "OZBlinky_dealloc" in content
