/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "platform/oz_platform.h"
#include "oz_dispatch.h"
#include "OZObject.h"

struct EmptyClass {
	struct OZObject base;
};

void EmptyClass_dealloc(struct EmptyClass *self);
