/* Auto-generated by oz_transpile -- do not edit */
#include "EmptyClass_ozh.h"
#include "OZObject_ozh.h"

OZ_SLAB_DEFINE(oz_slab_EmptyClass, sizeof(struct EmptyClass), 1, 4);

void EmptyClass_dealloc(struct EmptyClass *self)
{
	OZObject_dealloc((struct OZObject *)self);
}
