/* Auto-generated by oz_transpile -- do not edit */
#include "EmptyClass.h"
#include "oz_mem_slabs.h"

void EmptyClass_dealloc(struct EmptyClass *self)
{
	OZObject_dealloc((struct OZObject *)self);
}
