/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "platform/oz_platform.h"
#include <string.h>

#include "OZObject.h"
#include "EmptyClass.h"

extern oz_slab_t oz_slab_OZObject;
extern oz_slab_t oz_slab_EmptyClass;

static inline struct OZObject *OZObject_alloc(void)
{
	struct OZObject *obj;
	if (oz_slab_alloc(&oz_slab_OZObject, (void **)&obj) != 0) {
		return (struct OZObject *)0;
	}
	memset(obj, 0, sizeof(struct OZObject));
	obj->oz_class_id = OZ_CLASS_OZObject;
	oz_atomic_init(&obj->_refcount, 1);
	return obj;
}

static inline void OZObject_free(struct OZObject *obj)
{
	oz_slab_free(&oz_slab_OZObject, (void *)obj);
}

static inline struct EmptyClass *EmptyClass_alloc(void)
{
	struct EmptyClass *obj;
	if (oz_slab_alloc(&oz_slab_EmptyClass, (void **)&obj) != 0) {
		return (struct EmptyClass *)0;
	}
	memset(obj, 0, sizeof(struct EmptyClass));
	obj->base.oz_class_id = OZ_CLASS_EmptyClass;
	oz_atomic_init(&obj->base._refcount, 1);
	return obj;
}

static inline void EmptyClass_free(struct EmptyClass *obj)
{
	oz_slab_free(&oz_slab_EmptyClass, (void *)obj);
}

static inline void OZObject_dispatch_free(struct OZObject *obj)
{
	switch (obj->oz_class_id) {
	case OZ_CLASS_OZObject: OZObject_free((struct OZObject *)obj); break;
	case OZ_CLASS_EmptyClass: EmptyClass_free((struct EmptyClass *)obj); break;
	default: break;
	}
}

