/* Auto-generated by oz_transpile -- do not edit */
#pragma once

#include "oz/platform/oz_platform.h"
#include "oz_dispatch.h"

struct OZObject {
	enum oz_class_id oz_class_id;
	oz_atomic_t _refcount;
};

struct OZObject *OZObject_retain(struct OZObject *self);
void OZObject_release(struct OZObject *self);
uint32_t OZObject_retainCount(struct OZObject *self);
BOOL OZObject_isEqual_(struct OZObject *self, struct OZObject *anObject);
int OZObject_cDescription_maxLength_(struct OZObject *self, char *buf, int maxLen);

/* Refcount introspection — mirrors runtime __objc_refcount_get() */
#define __objc_refcount_get(obj) ((unsigned int)oz_atomic_get(&((struct OZObject *)(obj))->_refcount))
struct OZObject * OZObject_init(struct OZObject *self);
void OZObject_dealloc(struct OZObject *self);

